#!/usr/bin/env python3
"""Generate bestiary pages from data/creatures.json into src/content/docs/bestiary/.

One markdown page per creature, grouped into subdirectories (animals, monsters,
undead, elementals, humanoids, sea, bosses), plus an index page with group counts
and a notable-tamables table. All output is marked generated — never hand-edit;
fix tools/extract_creatures.py or this script and regenerate.

Usage: python3 tools/gen_bestiary.py
Stdlib only (Python 3.8+).
"""

import json
import os
import re
import shutil
from collections import OrderedDict

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(REPO_ROOT, "data", "creatures.json")
ANIM_PATH = os.path.join(REPO_ROOT, "data", "creature_anim.json")
SOUNDS_PATH = os.path.join(REPO_ROOT, "data", "creature_sounds.json")
APPEARANCE_PATH = os.path.join(REPO_ROOT, "data", "mob_appearance.json")
OUT_DIR = os.path.join(REPO_ROOT, "src", "content", "docs", "bestiary")

BANNER = "<!-- AUTO-GENERATED by tools/gen_bestiary.py from data/creatures.json — do not hand-edit -->"
LAST_VERIFIED = "2026-06-11"

GROUPS = OrderedDict([
    ("animals", "Animals"),
    ("monsters", "Monsters"),
    ("humanoids", "Humanoids"),
    ("undead", "Undead"),
    ("elementals", "Elementals"),
    ("sea", "Sea Creatures"),
    ("bosses", "Bosses & Champions"),
])

UNDEAD_KEYS = (
    "lich", "skelet", "zombie", "bone", "spectre", "specter", "ghost", "ghoul",
    "wraith", "mumm", "vampire", "shade", "rotting", "revenant", "deathknight",
    "bogle", "undead", "gore fiend", "gorefiend", "spectral",
)
SEA_KEYS = (
    "kraken", "leviathan", "dolphin", "seaserpent", "sea serpent", "squid",
    "charybdis", "osiredon", "scalis",
)
HUMANOID_KEYS = (
    "orc", "troll", "ogre", "ettin", "cyclop", "titan", "savage", "brigand",
    "pirate", "ratman", "lizardman", "juka", "meer", "minotaur", "gargoyle",
    "headless", "evil mage", "evilmage", "executioner", "barracoon", "harrower?",
    "mage lord", "berserker", "tribesman", "shaman", "champion of the", "kotl",
    "myrmidex?",  # insectoid, excluded via trailing '?'
)


def _match(keys, *texts):
    blob = " ".join(t.lower() for t in texts if t)
    return any(k in blob for k in keys if not k.endswith("?"))


def classify(c):
    cls = c["class"]
    name = c.get("name") or ""
    src = c["source"]
    if "/Bosses/" in src:
        return "bosses"
    if _match(SEA_KEYS, cls, name):
        return "sea"
    if "elemental" in cls.lower() or "elemental" in name.lower():
        return "elementals"
    if _match(UNDEAD_KEYS, cls, name):
        return "undead"
    if _match(HUMANOID_KEYS, cls, name):
        return "humanoids"
    if c.get("ai_type") == "AI_Animal":
        return "animals"
    return "monsters"


def camel_to_words(s):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", " ", s)


def display_name(c):
    name = c.get("name")
    if name:
        name = re.sub(r"^(a|an|the)\s+", "", name.strip(), flags=re.I)
        return name.title() if name else camel_to_words(c["class"])
    return camel_to_words(c["class"])


def slug(c):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", "-", c["class"]).lower()


def fmt_range(v, dash="–"):
    if isinstance(v, list):
        return f"{v[0]}{dash}{v[1]}"
    return str(v)


def yaml_str(s):
    return json.dumps(s, ensure_ascii=False)


def describe(c):
    bits = []
    if "hits" in c:
        bits.append(f"hits {fmt_range(c['hits'])}")
    if "damage" in c:
        bits.append(f"damage {fmt_range(c['damage'])}")
    if "ai_type" in c:
        bits.append(c["ai_type"].replace("AI_", "") + " AI")
    desc = f"{display_name(c)} — " + ", ".join(bits) if bits else display_name(c)
    if c.get("tamable"):
        mts = c.get("min_tame_skill")
        desc += f"; tamable{f' at {mts} Animal Taming' if mts is not None else ''}"
    return desc + "."


# Layers treated as "wielded" (a weapon) vs "worn" for the prose.
WIELD_LAYERS = {"OneHanded", "TwoHanded"}


def _join_words(parts):
    """Oxford-free 'a, b and c' joiner for the appearance sentence."""
    parts = [p for p in parts if p]
    if not parts:
        return ""
    if len(parts) == 1:
        return parts[0]
    return ", ".join(parts[:-1]) + " and " + parts[-1]


def _item_phrase(w):
    """Lowercase item name with an article, noting dyed pieces.

    items.json names often already carry an article ('a bow', 'an orcish bow');
    strip it first so we don't double up, then re-derive based on the (possibly
    'dyed'-prefixed) noun."""
    name = (w.get("name") or camel_to_words(w["class"])).lower()
    name = re.sub(r"^(?:a|an|the)\s+", "", name)
    if w.get("hue_random"):
        name = "dyed " + name
    # plural-ish pieces (arms/legs/boots/pants/gloves) read better without article
    if re.search(r"(arms|legs|boots|pants|gloves|mitts|sandals|greaves)$", name):
        return name
    art = "an" if name[:1] in "aeiou" else "a"
    return f"{art} {name}"


def appearance_prose(worn):
    """One sentence: what the creature wears and wields, from the worn list."""
    worn_items = [w for w in worn if w.get("layer") not in WIELD_LAYERS]
    wield_items = [w for w in worn if w.get("layer") in WIELD_LAYERS]

    def group_phrases(items, collapse_optional=False):
        # Group optional alternatives into a single "one of: a, b, c" choice;
        # required pieces are listed plainly. When collapse_optional is set, ALL
        # optional pieces share one choice (a creature picks one weapon total,
        # even across the One/TwoHanded layers); otherwise they group by layer
        # (so a random shirt and a random hat stay distinct slots).
        by_layer_opt = {}
        order = []
        for w in items:
            if w.get("optional"):
                key = "_one" if collapse_optional else (w.get("layer") or w["class"])
                if key not in by_layer_opt:
                    by_layer_opt[key] = []
                    order.append(("opt", key))
                by_layer_opt[key].append(w)
            else:
                order.append(("req", w))
        phrases = []
        for kind, val in order:
            if kind == "req":
                phrases.append(_item_phrase(val))
            else:
                alts = by_layer_opt[val]
                if len(alts) == 1:
                    phrases.append("sometimes " + _item_phrase(alts[0]))
                else:
                    names = _join_words([_item_phrase(a) for a in alts])
                    phrases.append("one of: " + names)
        return phrases

    bits = []
    wp = group_phrases(worn_items)
    if wp:
        bits.append("Wears " + _join_words(wp))
    vp = group_phrases(wield_items, collapse_optional=True)
    if vp:
        verb = "wields " if bits else "Wields "
        bits.append(verb + _join_words(vp))
    if not bits:
        return ""
    return ", and ".join(bits).rstrip() + "."


def appearance_section(c, appearance):
    """Markdown lines for the ## Appearance section, or [] if not applicable."""
    entry = appearance.get(c["class"]) if appearance else None
    if not entry or not entry.get("worn"):
        return []
    worn = entry["worn"]
    name = display_name(c)
    lines = ["## Appearance", ""]
    prose = appearance_prose(worn)
    if prose:
        lines += [prose, ""]
    if entry.get("paperdoll"):
        lines += [
            f'<img src="{entry["paperdoll"]}" alt="{name} equipped" width="220" />',
            "",
        ]
    # Worn-item table: icon + name (+ optional/dyed note).
    lines += ["| | Item | Slot | |", "|---|---|---|---|"]
    for w in worn:
        icon = (f'<img src="{w["png"]}" class="uo-sprite" alt="" width="56" />'
                if w.get("png") else "")
        nm = w.get("name") or camel_to_words(w["class"])
        notes = []
        if w.get("optional"):
            notes.append("random")
        if w.get("hue_random"):
            notes.append("dyed")
        slotname = w.get("layer") or "—"
        note = ", ".join(notes)
        lines.append(f"| {icon} | {nm} | {slotname} | {note} |")
    lines += ["",
              "See the [paperdoll layer reference](/reference/paperdoll/) for how "
              "equipment is composited.", ""]
    return lines


def creature_page(c, group, anim_data=None, sounds_data=None, appearance=None):
    name = display_name(c)
    lines = [
        "---",
        f"title: {yaml_str(name)}",
        f"description: {yaml_str(describe(c))}",
        "status: source-verified",
        "generated: true",
        "sources:",
        f"  - {yaml_str('servuo: ' + c['source'])}",
        f"last_verified: {LAST_VERIFIED}",
        "---",
        BANNER,
        "",
    ]

    # Add GIF if available
    if anim_data and c["class"] in anim_data["creatures"]:
        body_id = anim_data["creatures"][c["class"]]
        if str(body_id) in anim_data["bodies"]:
            gif_path = anim_data["bodies"][str(body_id)]["gif"]
            lines.append(f'<img src="{gif_path}" class="uo-anim" alt="{name} animation" />')
            lines.append("")

    facts = []
    if c.get("name"):
        facts.append(("In-game name", c["name"]))
    elif c.get("name_list"):
        facts.append(("In-game name", f"random (`{c['name_list']}` name list)"))
    if c.get("corpse_name"):
        facts.append(("Corpse", c["corpse_name"]))
    if "body" in c:
        b = c["body"]
        facts.append(("Body ID", ", ".join(str(x) for x in b) if isinstance(b, list) else str(b)))
    if "base_sound_id" in c:
        facts.append(("Base sound ID", str(c["base_sound_id"])))
    if "ai_type" in c:
        facts.append(("AI", c["ai_type"]))
    if "fight_mode" in c:
        facts.append(("Fight mode", c["fight_mode"]))
    if "fame" in c:
        facts.append(("Fame", str(c["fame"])))
    if "karma" in c:
        facts.append(("Karma", str(c["karma"])))
    if "virtual_armor" in c:
        facts.append(("Virtual armor", str(c["virtual_armor"])))
    facts.append(("Script", f"`{c['source']}`"))
    lines += ["| | |", "|---|---|"]
    lines += [f"| **{k}** | {v} |" for k, v in facts]
    lines.append("")

    stat_rows = [(label, c[key]) for label, key in
                 (("Strength", "str"), ("Dexterity", "dex"), ("Intelligence", "int"),
                  ("Hits", "hits"), ("Stamina", "stam"), ("Mana", "mana"),
                  ("Damage", "damage")) if key in c]
    if stat_rows:
        lines += ["## Stats", "", "| Stat | Value |", "|---|---|"]
        lines += [f"| {label} | {fmt_range(v)} |" for label, v in stat_rows]
        if c.get("damage_types"):
            dt = ", ".join(f"{k} {v}%" for k, v in c["damage_types"].items())
            lines.append(f"| Damage type | {dt} |")
        lines.append("")

    if c.get("resistances"):
        lines += ["## Resistances", "", "| Physical | Fire | Cold | Poison | Energy |",
                  "|---|---|---|---|---|"]
        row = [fmt_range(c["resistances"].get(k, 0))
               for k in ("Physical", "Fire", "Cold", "Poison", "Energy")]
        lines += ["| " + " | ".join(row) + " |", ""]

    if c.get("skills"):
        lines += ["## Skills", "", "| Skill | Value |", "|---|---|"]
        lines += [f"| {k} | {fmt_range(v)} |" for k, v in sorted(c["skills"].items())]
        lines.append("")

    lines += appearance_section(c, appearance)

    loot = c.get("loot") or {}
    res_rows = [(label, c[key]) for label, key in
                (("Meat", "meat"), ("Hides", "hides"), ("Feathers", "feathers"),
                 ("Wool", "wool")) if key in c]
    if loot or res_rows:
        lines += ["## Loot & resources", ""]
        if loot.get("packs"):
            lines += ["| Loot pack | Count |", "|---|---|"]
            lines += [f"| {p['pack']} | {p['count']} |" for p in loot["packs"]]
            lines.append("")
        if loot.get("pack_gold"):
            lines += [f"- Gold: {fmt_range(loot['pack_gold'])}"]
        if loot.get("pack_items"):
            items = ", ".join(camel_to_words(i) for i in loot["pack_items"])
            lines += [f"- Pack items (some chance-based): {items}"]
        if loot.get("pack_gold") or loot.get("pack_items"):
            lines.append("")
        if res_rows:
            hide_note = f" ({c['hide_type'].lower()})" if c.get("hide_type") else ""
            carve = ", ".join(
                f"{v} {label.lower()}{hide_note if label == 'Hides' else ''}"
                for label, v in res_rows)
            lines += [f"Carve: {carve}.", ""]

    if c.get("tamable"):
        lines += ["## Taming", "", "| | |", "|---|---|"]
        if c.get("min_tame_skill") is not None:
            lines.append(f"| **Min taming skill** | {c['min_tame_skill']} |")
        if c.get("control_slots") is not None:
            lines.append(f"| **Control slots** | {c['control_slots']} |")
        lines.append("")

    # Add Sounds section if available
    if sounds_data and c["class"] in sounds_data["creatures"]:
        base_sound_id = sounds_data["creatures"][c["class"]]
        if str(base_sound_id) in sounds_data["sounds"]:
            sounds = sounds_data["sounds"][str(base_sound_id)]
            lines += ["## Sounds", ""]
            anger_src = sounds["anger"]
            idle_src = sounds["idle"]
            attack_src = sounds["attack"]
            hurt_src = sounds["hurt"]
            death_src = sounds["death"]
            lines.append(f'**Anger** <audio controls preload="none" src="{anger_src}"></audio>')
            lines.append("")
            lines.append(f'**Idle** <audio controls preload="none" src="{idle_src}"></audio>')
            lines.append("")
            lines.append(f'**Attack** <audio controls preload="none" src="{attack_src}"></audio>')
            lines.append("")
            lines.append(f'**Hurt** <audio controls preload="none" src="{hurt_src}"></audio>')
            lines.append("")
            lines.append(f'**Death** <audio controls preload="none" src="{death_src}"></audio>')
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def index_page(grouped, creatures, anim_data=None):
    total = len(creatures)
    lines = [
        "---",
        "title: Bestiary",
        f"description: Creature reference for our shard — {total} creatures extracted from ServUO source.",
        "status: source-verified",
        "generated: true",
        "sources:",
        '  - "servuo: Scripts/Mobiles/ (via tools/extract_creatures.py)"',
        f"last_verified: {LAST_VERIFIED}",
        "---",
        BANNER,
        "",
        f"Stats for **{total} creatures**, extracted directly from the ServUO scripts that",
        "run this shard (`Scripts/Mobiles/`). Every page is generated — to fix an error,",
        "file a discrepancy report; never hand-edit these pages.",
        "",
        "## Groups",
        "",
        "| | Group | Creatures |",
        "|---|---|---|",
    ]
    for gkey, gtitle in GROUPS.items():
        members = grouped.get(gkey, [])
        # representative thumbnail: first member of this group that has a GIF
        thumb = ""
        for c in sorted(members, key=display_name):
            t = _anim_thumb(c, anim_data, gtitle)
            if t:
                thumb = t
                break
        lines.append(f"| {thumb} | [{gtitle}](/bestiary/{gkey}/) | {len(members)} |")
    lines += ["", "## Notable tamables", "",
              "The hardest tames on the shard, by minimum Animal Taming skill.", "",
              "| | Creature | Group | Min taming | Slots | Hits |",
              "|---|---|---|---|---|---|"]
    tames = sorted(
        (c for c in creatures if c.get("tamable") and c.get("min_tame_skill") is not None),
        key=lambda c: -c["min_tame_skill"])[:20]
    for c in tames:
        g = classify(c)
        name = display_name(c)
        link = f"[{name}](/bestiary/{g}/{slug(c)}/)"
        lines.append(f"| {_anim_thumb(c, anim_data, name)} | {link} | {GROUPS[g]} | {c['min_tame_skill']} | "
                     f"{c.get('control_slots', '—')} | {fmt_range(c.get('hits', '—'))} |")
    lines += ["",
              f"All {sum(1 for c in creatures if c.get('tamable'))} tamable creatures have a",
              "**Taming** section on their page.", ""]
    return "\n".join(lines)


def _anim_thumb(c, anim_data, name):
    """An animated-GIF thumbnail cell for a creature, or empty if it has none."""
    if anim_data and c["class"] in anim_data.get("creatures", {}):
        body_id = anim_data["creatures"][c["class"]]
        body = anim_data.get("bodies", {}).get(str(body_id))
        if body:
            return f'<img src="{body["gif"]}" class="uo-anim" alt="{name}" loading="lazy" />'
    return ""


def group_index_page(gkey, gtitle, members, anim_data=None):
    lines = [
        "---",
        f"title: {yaml_str(gtitle)}",
        f"description: {yaml_str(f'{gtitle} — {len(members)} creatures, stats from ServUO source.')}",
        "status: source-verified",
        "generated: true",
        "sources:",
        '  - "servuo: Scripts/Mobiles/ (via tools/extract_creatures.py)"',
        '  - "client: anim*.mul (via tools/extract_anim.py)"',
        f"last_verified: {LAST_VERIFIED}",
        "---",
        BANNER,
        "",
        "| | Creature | Hits | Damage | Tamable |",
        "|---|---|---|---|---|",
    ]
    for c in sorted(members, key=display_name):
        tame = f"yes ({c['min_tame_skill']})" if c.get("tamable") and c.get("min_tame_skill") is not None \
            else ("yes" if c.get("tamable") else "—")
        name = display_name(c)
        lines.append(f"| {_anim_thumb(c, anim_data, name)} | [{name}](/bestiary/{gkey}/{slug(c)}/) "
                     f"| {fmt_range(c.get('hits', '—'))} | {fmt_range(c.get('damage', '—'))} | {tame} |")
    lines.append("")
    return "\n".join(lines)


def main():
    with open(DATA_PATH, encoding="utf-8") as f:
        data = json.load(f)
    creatures = data["creatures"]

    # Load animation and sound data
    with open(ANIM_PATH, encoding="utf-8") as f:
        anim_data = json.load(f)
    with open(SOUNDS_PATH, encoding="utf-8") as f:
        sounds_data = json.load(f)
    appearance = {}
    if os.path.exists(APPEARANCE_PATH):
        with open(APPEARANCE_PATH, encoding="utf-8") as f:
            appearance = json.load(f).get("creatures", {})

    # Remove previously generated output (everything under bestiary/ is owned by
    # this script; only files carrying the banner are deleted, as a safety net).
    if os.path.isdir(OUT_DIR):
        for dirpath, _dirs, files in os.walk(OUT_DIR, topdown=False):
            for fn in files:
                p = os.path.join(dirpath, fn)
                if fn.endswith((".md", ".mdx")):
                    with open(p, encoding="utf-8") as f:
                        if BANNER in f.read():
                            os.remove(p)
            if dirpath != OUT_DIR and not os.listdir(dirpath):
                shutil.rmtree(dirpath)

    grouped = {}
    for c in creatures:
        grouped.setdefault(classify(c), []).append(c)

    pages = 0
    for gkey, members in grouped.items():
        gdir = os.path.join(OUT_DIR, gkey)
        os.makedirs(gdir, exist_ok=True)
        with open(os.path.join(gdir, "index.md"), "w", encoding="utf-8") as f:
            f.write(group_index_page(gkey, GROUPS[gkey], members, anim_data))
        for c in members:
            with open(os.path.join(gdir, slug(c) + ".md"), "w", encoding="utf-8") as f:
                f.write(creature_page(c, gkey, anim_data, sounds_data, appearance))
            pages += 1

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "index.md"), "w", encoding="utf-8") as f:
        f.write(index_page(grouped, creatures, anim_data))

    print(f"wrote {pages} creature pages + {len(grouped)} group indexes + 1 bestiary index")
    for gkey in GROUPS:
        print(f"  {gkey}: {len(grouped.get(gkey, []))}")


if __name__ == "__main__":
    main()
