#!/usr/bin/env python3
"""Generate src/content/docs/magic/ from data/spells.json.

Produces:
  magic/index.md                  — spellbook overview (circle table + spell lists)
  magic/reagents.md               — the 8 reagents and which spells use each
  magic/circle-<n>/<slug>.md      — one page per spell (64 pages)

All pages are marked generated: true with an AUTO-GENERATED banner.
Never hand-edit the output; fix tools/extract_spells.py or this generator
and re-run. Usage: python3 tools/gen_spells.py
Stdlib only.
"""

import datetime
import json
from pathlib import Path

WIKI_ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = WIKI_ROOT / "data" / "spells.json"
OUT_DIR = WIKI_ROOT / "src" / "content" / "docs" / "magic"

BANNER = "<!-- AUTO-GENERATED by tools/gen_spells.py from data/spells.json — do not hand-edit -->"
TODAY = datetime.date.today().isoformat()

CIRCLE_WORDS = {
    1: "First", 2: "Second", 3: "Third", 4: "Fourth",
    5: "Fifth", 6: "Sixth", 7: "Seventh", 8: "Eighth",
}

REAGENT_SLUGS = [
    "Black Pearl", "Bloodmoss", "Garlic", "Ginseng",
    "Mandrake Root", "Nightshade", "Spiders' Silk", "Sulfurous Ash",
]

REAGENT_BLURBS = {
    "Black Pearl": "Associated with projection and force; common in energy and travel magic.",
    "Bloodmoss": "Associated with movement; common in travel, summoning and agility magic.",
    "Garlic": "Associated with warding; common in protective and curative magic.",
    "Ginseng": "Associated with healing and restoration.",
    "Mandrake Root": "Associated with power; the workhorse reagent of high-circle magic.",
    "Nightshade": "Associated with poison and curses.",
    "Spiders' Silk": "Associated with binding and summoning.",
    "Sulfurous Ash": "Associated with fire and energy.",
}


def yaml_str(s: str) -> str:
    """Quote a string safely for YAML (JSON strings are valid YAML scalars)."""
    return json.dumps(s, ensure_ascii=False)


def frontmatter(title: str, description: str, sources: list) -> str:
    lines = [
        "---",
        f"title: {yaml_str(title)}",
        f"description: {yaml_str(description)}",
        "status: source-verified",
        "generated: true",
        "sources:",
    ]
    for s in sources:
        lines.append(f"  - {yaml_str(s)}")
    lines += [
        f"last_verified: {TODAY}",
        "---",
        "",
        BANNER,
        "",
        "",
    ]
    return "\n".join(lines)


def fmt_skill(v: float) -> str:
    return f"{max(v, 0.0):g}"


def spell_link(spell: dict) -> str:
    return f"[{spell['name']}](/magic/circle-{spell['circle']}/{spell['slug']}/)"


def gen_spell_page(spell: dict, circles: dict) -> str:
    c = spell["circle"]
    ct = circles[str(c)]
    fm = frontmatter(
        spell["name"],
        spell["description"],
        [f"servuo: {spell['source']}", "servuo: Scripts/Spells/Base/MagerySpell.cs"],
    )
    reagent_list = ", ".join(spell["reagents"])
    body = f"""*{spell['mantra']}* — {CIRCLE_WORDS[c]} Circle Magery

{spell['description']}

## Casting requirements

| | |
| --- | --- |
| Circle | {c} ({CIRCLE_WORDS[c]}) |
| Mana cost | {ct['mana']} |
| Minimum Magery | {fmt_skill(ct['min_skill'])} (0% success below this) |
| Magery for 100% success | {fmt_skill(ct['max_skill'])} |
| Reagents | {reagent_list} |
| Words of power | {spell['mantra']} |

Casting from a scroll lowers the effective circle by two, reducing the skill
requirement (mana cost is unchanged).

## See also

- [Spellbook overview](/magic/)
- [Reagents](/magic/reagents/)
"""
    return fm + body


def gen_index(spells: list, circles: dict) -> str:
    fm = frontmatter(
        "Magery Spellbook",
        "All 64 Magery spells by circle, with mana costs and skill requirements.",
        [
            "servuo: Scripts/Spells/Base/MagerySpell.cs",
            "servuo: Scripts/Spells/First..Eighth (spell registrations)",
        ],
    )
    out = [fm]
    out.append(
        "The Magery spellbook holds 64 spells in 8 circles. Each circle has a fixed "
        "mana cost and a Magery skill band: below the minimum the cast always fails, "
        "at or above the maximum it never fizzles. Casting from a scroll counts as "
        "two circles lower for the skill check."
    )
    out += ["", "## Circles", ""]
    out.append("| Circle | Mana | Min Magery (0% success) | Magery for 100% |")
    out.append("| --- | --- | --- | --- |")
    for n in range(1, 9):
        ct = circles[str(n)]
        out.append(
            f"| {n} ({CIRCLE_WORDS[n]}) | {ct['mana']} | "
            f"{fmt_skill(ct['min_skill'])} | {fmt_skill(ct['max_skill'])} |"
        )
    out += ["", "Skill values come from `MagerySpell.GetCastSkills` "
            "(success chance ramps linearly across the 40-point band).", ""]

    for n in range(1, 9):
        out.append(f"## Circle {n} — {CIRCLE_WORDS[n]}")
        out.append("")
        out.append("| Spell | Words of power | Reagents |")
        out.append("| --- | --- | --- |")
        for s in [s for s in spells if s["circle"] == n]:
            out.append(f"| {spell_link(s)} | *{s['mantra']}* | {', '.join(s['reagents'])} |")
        out.append("")

    out.append("See also: [Reagents](/magic/reagents/)")
    out.append("")
    return "\n".join(out)


def gen_reagents(spells: list) -> str:
    fm = frontmatter(
        "Reagents",
        "The eight Magery reagents and every spell that consumes each one.",
        ["servuo: Scripts/Spells/Reagent.cs",
         "servuo: Scripts/Spells/First..Eighth (spell registrations)"],
    )
    out = [fm]
    out.append(
        "Every Magery spell consumes one of each listed reagent per cast "
        "(unless the caster has Lower Reagent Cost or uses an arcane gem)."
    )
    out.append("")
    for reagent in REAGENT_SLUGS:
        users = [s for s in spells if reagent in s["reagents"]]
        out.append(f"## {reagent}")
        out.append("")
        out.append(REAGENT_BLURBS[reagent])
        out.append("")
        out.append(f"Used by {len(users)} spells:")
        out.append("")
        for s in users:
            out.append(f"- {spell_link(s)} (circle {s['circle']})")
        out.append("")
    out.append("See also: [Spellbook overview](/magic/)")
    out.append("")
    return "\n".join(out)


def main():
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    spells, circles = data["spells"], data["circles"]

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Clean previously generated spell pages so renames don't leave orphans.
    for old in OUT_DIR.rglob("*.md"):
        if BANNER in old.read_text(encoding="utf-8"):
            old.unlink()

    written = 0
    (OUT_DIR / "index.md").write_text(gen_index(spells, circles), encoding="utf-8")
    (OUT_DIR / "reagents.md").write_text(gen_reagents(spells), encoding="utf-8")
    written += 2

    for spell in spells:
        d = OUT_DIR / f"circle-{spell['circle']}"
        d.mkdir(exist_ok=True)
        (d / f"{spell['slug']}.md").write_text(gen_spell_page(spell, circles), encoding="utf-8")
        written += 1

    print(f"Wrote {written} pages under {OUT_DIR}")


if __name__ == "__main__":
    main()
