#!/usr/bin/env python3
"""Generate src/content/docs/crafting/ pages from data/recipes.json.

Produces crafting/index.md (overview) plus one page per craft system with
recipes in markdown tables grouped by category. All pages are marked
`generated: true` — never hand-edit them; fix tools/extract_crafting.py
or the source data and regenerate.

Usage: python3 tools/gen_crafting.py
"""

import datetime
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from i18n_labels import LOCALES, L, SKILL, locale_prefix  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(ROOT, "data", "recipes.json")
ITEM_ART_PATH = os.path.join(ROOT, "data", "item_art.json")
EXPANSION_PATH = os.path.join(ROOT, "data", "item_expansion.json")
WEAPONS_PATH = os.path.join(ROOT, "data", "weapons.json")
ARMOR_PATH = os.path.join(ROOT, "data", "armor.json")
DOCS_ROOT = os.path.join(ROOT, "src", "content", "docs")


def out_dir(locale):
    """crafting/ output dir for a locale ('' prefix for English)."""
    base = DOCS_ROOT if locale == "en" else os.path.join(DOCS_ROOT, locale)
    return os.path.join(base, "crafting")

BANNER = ("<!-- AUTO-GENERATED by tools/gen_crafting.py from data/recipes.json"
          " — do not hand-edit -->")

TODAY = datetime.date.today().isoformat()


def md_escape(s):
    """Make a string safe inside a markdown table cell (and for Starlight)."""
    return (s.replace("|", "\\|")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
             .replace("{", "&#123;")
             .replace("}", "&#125;")
             .replace("\n", " "))


def frontmatter(title, description, sources):
    lines = [
        "---",
        "title: %s" % json.dumps(title),
        "description: %s" % json.dumps(description),
        "status: source-verified",
        "generated: true",
        "sources:",
    ]
    lines += ['  - "%s"' % s for s in sources]
    lines += ["last_verified: %s" % TODAY, "---", "", BANNER, ""]
    return "\n".join(lines)


def skill_cell(recipe, main_skill, locale):
    parts = ["%.1f – %.1f" % (recipe["min_skill"], recipe["max_skill"])]
    if recipe.get("craft_skill") and recipe["craft_skill"] != main_skill:
        parts[0] = "%s %s" % (SKILL(locale, recipe["craft_skill"]), parts[0])
    for sk in recipe.get("skills", []):
        parts.append("%s %.1f – %.1f" % (SKILL(locale, sk["skill"]), sk["min"], sk["max"]))
    return "; ".join(parts)


def materials_cell(recipe):
    parts = []
    for res in recipe["resources"]:
        name = res["name"] or res["type"]
        if name.startswith("cliloc:"):
            name = res["type"]
        parts.append("%d %s" % (res["amount"], md_escape(name)))
    return ", ".join(parts)


def era_cell(recipe, expansion):
    """Era label for the recipe's item_type, or '' if unknown."""
    item_type = recipe.get("item_type")
    if item_type and item_type in expansion:
        return expansion[item_type]
    return ""


def stats_cell(recipe, weapons, armor):
    """Combat/defense stats for the recipe's crafted item, joined by class.

    Weapons -> 'min–max dmg · speed · hands · str'; armor -> resist tuple · str;
    shields -> 'AR n · str'. Returns '' for items with no weapon/armor stats
    (reagents, food, tools, etc.).
    """
    item_type = recipe.get("item_type")
    if not item_type:
        return ""
    w = weapons.get(item_type)
    if w:
        parts = ["%d–%d dmg" % (w["min_damage"], w["max_damage"]),
                 "%.1fs" % w["ml_speed"]]
        hands = {"One-handed": "1H", "Two-handed": "2H"}.get(w.get("hands"))
        if hands:
            parts.append(hands)
        if w.get("str_req"):
            parts.append("str %d" % w["str_req"])
        return " · ".join(parts)
    p = armor.get(item_type)
    if p:
        if p.get("is_shield"):
            parts = []
            if p.get("armor_base"):
                parts.append("AR %d" % p["armor_base"])
            if p.get("str_req_aos"):
                parts.append("str %d" % p["str_req_aos"])
            return " · ".join(parts)
        r = p.get("base_resist") or {}
        parts = ["%d/%d/%d/%d/%d" % (r.get("phys") or 0, r.get("fire") or 0,
                                     r.get("cold") or 0, r.get("poison") or 0,
                                     r.get("energy") or 0)]
        if p.get("str_req_aos"):
            parts.append("str %d" % p["str_req_aos"])
        return " · ".join(parts)
    return ""


def icon_cell(recipe, item_art):
    """Generate an icon cell for the recipe's item_type.

    Returns an img tag if the item is in item_art.json, otherwise empty string.
    """
    item_type = recipe.get("item_type")
    if item_type and item_type in item_art:
        png = item_art[item_type]["png"]
        return '<img src="%s" class="uo-sprite" alt="" width="56" />' % png
    return ""


def gen_system_page(slug, sysdata, item_art, expansion, weapons, armor, locale):
    system = sysdata["system"]
    main_skill = sysdata["main_skill"]
    recipes = sysdata["recipes"]

    # group by category, preserving source order
    categories = {}
    for r in recipes:
        categories.setdefault(r["category"], []).append(r)

    # Only show the Stats column for systems that actually craft weapons/armor
    # (blacksmithy, tailoring, etc.) — leave alchemy/cooking/inscription tables clean.
    has_stats = any(stats_cell(r, weapons, armor) for r in recipes)

    # Proper-noun craft-system/skill names stay English; prose is translated.
    desc = L(locale, "craft.system_desc",
             n=len(recipes), system=system, skill=SKILL(locale, main_skill))
    out = [frontmatter(system, desc, ["servuo: " + sysdata["source"]])]
    out.append(L(locale, "craft.main_recipes",
                 skill=SKILL(locale, main_skill), n=len(recipes)) + "\n")
    out.append(L(locale, "craft.skill_range_note") + "\n")
    if has_stats:
        out.append(L(locale, "craft.stats_note") + "\n")

    if has_stats:
        hdr = ("|  | %s | %s | %s | %s | %s |" % (
            L(locale, "col.item"), L(locale, "col.skill"), L(locale, "col.stats"),
            L(locale, "col.era"), L(locale, "col.materials")))
        sep = "| --- | --- | --- | --- | --- | --- |"
    else:
        hdr = ("|  | %s | %s | %s | %s |" % (
            L(locale, "col.item"), L(locale, "col.skill"),
            L(locale, "col.era"), L(locale, "col.materials")))
        sep = "| --- | --- | --- | --- | --- |"
    for cat, items in categories.items():
        # Recipe category names are domain groupings — kept English (proper nouns).
        out.append("## %s\n" % md_escape(cat.title() if cat.islower() else cat))
        out.append(hdr)
        out.append(sep)
        for r in items:
            name = r["name"] or r["item_type"]
            if name.startswith("cliloc:"):
                name = r["item_type"]
            if has_stats:
                out.append("| %s | %s | %s | %s | %s | %s |" % (
                    icon_cell(r, item_art), md_escape(name),
                    skill_cell(r, main_skill, locale),
                    md_escape(stats_cell(r, weapons, armor)),
                    era_cell(r, expansion), materials_cell(r)))
            else:
                out.append("| %s | %s | %s | %s | %s |" % (
                    icon_cell(r, item_art), md_escape(name),
                    skill_cell(r, main_skill, locale),
                    era_cell(r, expansion), materials_cell(r)))
        out.append("")

    path = os.path.join(out_dir(locale), slug + ".md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out).rstrip() + "\n")
    return path


def gen_index(systems, locale):
    pfx = locale_prefix(locale)
    desc = L(locale, "craft.index_desc", n=len(systems))
    sources = ["servuo: " + s["source"] for _, s in systems]
    out = [frontmatter(L(locale, "craft.index_title"), desc, sources)]
    total = sum(len(s["recipes"]) for _, s in systems)
    out.append(L(locale, "craft.index_intro", n=len(systems), total=total) + "\n")
    out.append("| %s | %s | %s |" % (
        L(locale, "col.craft_system"), L(locale, "col.main_skill"),
        L(locale, "col.recipes")))
    out.append("| --- | --- | --- |")
    for slug, s in systems:
        out.append("| [%s](%s/crafting/%s/) | %s | %d |" % (
            s["system"], pfx, slug, SKILL(locale, s["main_skill"]),
            len(s["recipes"])))
    out.append("")

    path = os.path.join(out_dir(locale), "index.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out).rstrip() + "\n")
    return path


def main():
    with open(DATA_PATH, encoding="utf-8") as f:
        data = json.load(f)

    with open(ITEM_ART_PATH, encoding="utf-8") as f:
        item_art_data = json.load(f)
    item_art = item_art_data.get("items", {})

    with open(EXPANSION_PATH, encoding="utf-8") as f:
        expansion = json.load(f).get("by_class", {})

    with open(WEAPONS_PATH, encoding="utf-8") as f:
        weapons = {w["class"]: w for w in json.load(f).get("weapons", [])}

    with open(ARMOR_PATH, encoding="utf-8") as f:
        armor = {p["class"]: p for p in json.load(f).get("pieces", [])}

    systems = [(slug, s) for slug, s in data.items() if slug != "_schema"]
    systems.sort(key=lambda kv: kv[0])

    for locale in LOCALES:
        os.makedirs(out_dir(locale), exist_ok=True)
        for slug, s in systems:
            path = gen_system_page(slug, s, item_art, expansion, weapons, armor, locale)
            print("wrote %s (%d recipes)" % (os.path.relpath(path, ROOT),
                                             len(s["recipes"])))
        path = gen_index(systems, locale)
        print("wrote %s" % os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
