#!/usr/bin/env python3
"""Generate src/content/docs/magic/ from data/spells.json.

Produces:
  magic/index.md                  — spellbook overview (circle table + spell lists)
  magic/reagents.md               — the 8 reagents and which spells use each
  magic/circle-<n>/<slug>.md      — one page per spell (64 pages)

All pages are marked generated: true with an AUTO-GENERATED banner.
Never hand-edit the output; fix tools/extract_spells.py or this generator
and re-run. Usage: python3 tools/gen_spells.py
Stdlib only.
"""

import datetime
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from i18n_labels import LOCALES, L, locale_prefix  # noqa: E402

WIKI_ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = WIKI_ROOT / "data" / "spells.json"
SPELL_ICONS_PATH = WIKI_ROOT / "data" / "spell_icons.json"
DOCS_ROOT = WIKI_ROOT / "src" / "content" / "docs"


def out_dir(locale):
    base = DOCS_ROOT if locale == "en" else DOCS_ROOT / locale
    return base / "magic"


def circle_word(locale, n):
    """Localized ordinal for a circle ('First'…'Eighth')."""
    return L(locale, "circ." + CIRCLE_WORDS[n])

BANNER = "<!-- AUTO-GENERATED by tools/gen_spells.py from data/spells.json — do not hand-edit -->"
TODAY = datetime.date.today().isoformat()

CIRCLE_WORDS = {
    1: "First", 2: "Second", 3: "Third", 4: "Fourth",
    5: "Fifth", 6: "Sixth", 7: "Seventh", 8: "Eighth",
}

REAGENT_SLUGS = [
    "Black Pearl", "Bloodmoss", "Garlic", "Ginseng",
    "Mandrake Root", "Nightshade", "Spiders' Silk", "Sulfurous Ash",
]

REAGENT_BLURBS = {
    "Black Pearl": "Associated with projection and force; common in energy and travel magic.",
    "Bloodmoss": "Associated with movement; common in travel, summoning and agility magic.",
    "Garlic": "Associated with warding; common in protective and curative magic.",
    "Ginseng": "Associated with healing and restoration.",
    "Mandrake Root": "Associated with power; the workhorse reagent of high-circle magic.",
    "Nightshade": "Associated with poison and curses.",
    "Spiders' Silk": "Associated with binding and summoning.",
    "Sulfurous Ash": "Associated with fire and energy.",
}


def yaml_str(s: str) -> str:
    """Quote a string safely for YAML (JSON strings are valid YAML scalars)."""
    return json.dumps(s, ensure_ascii=False)


def frontmatter(title: str, description: str, sources: list) -> str:
    lines = [
        "---",
        f"title: {yaml_str(title)}",
        f"description: {yaml_str(description)}",
        "status: source-verified",
        "generated: true",
        "sources:",
    ]
    for s in sources:
        lines.append(f"  - {yaml_str(s)}")
    lines += [
        f"last_verified: {TODAY}",
        "---",
        "",
        BANNER,
        "",
        "",
    ]
    return "\n".join(lines)


def fmt_skill(v: float) -> str:
    return f"{max(v, 0.0):g}"


def spell_link(spell: dict, locale: str = "en") -> str:
    # Spell display name is a proper noun — kept English.
    pfx = locale_prefix(locale)
    return f"[{spell['name']}]({pfx}/magic/circle-{spell['circle']}/{spell['slug']}/)"


def gen_spell_page(spell: dict, spell_id: int, circles: dict, spell_icons: dict, locale: str) -> str:
    c = spell["circle"]
    ct = circles[str(c)]
    cword = circle_word(locale, c)
    fm = frontmatter(
        spell["name"],
        spell["description"],
        [f"servuo: {spell['source']}", "servuo: Scripts/Spells/Base/MagerySpell.cs"],
    )
    reagent_list = ", ".join(spell["reagents"])

    # Find spell icon entry by id
    spell_id_str = str(spell_id)
    icon_html = ""
    if spell_id_str in spell_icons.get("icons", {}):
        icon_html = f'<img src="/img/spells/{spell_id_str}.png" class="uo-sprite" alt="{spell["name"]} spell icon" width="72" height="72" />\n\n'

    mantra_note = L(locale, "spell.mantra_note", word=cword)
    body = f"""{icon_html}<p class="uo-runic" title="{spell['mantra']}">{spell['mantra']}</p>

<span class="uo-ascii">{spell['mantra']}</span> — {mantra_note}

{spell['description']}

## {L(locale, "spell.casting_requirements")}

| | |
| --- | --- |
| {L(locale, "col.circle")} | {c} ({cword}) |
| {L(locale, "spell.mana_cost")} | {ct['mana']} |
| {L(locale, "spell.min_magery")} | {fmt_skill(ct['min_skill'])} {L(locale, "spell.min_magery_note")} |
| {L(locale, "spell.magery_100")} | {fmt_skill(ct['max_skill'])} |
| {L(locale, "col.reagents")} | {reagent_list} |
| {L(locale, "col.words_of_power")} | <span class="uo-runic">{spell['mantra']}</span> &nbsp; <span class="uo-ascii">{spell['mantra']}</span> |

{L(locale, "spell.scroll_note")}

## {L(locale, "magic.see_also")}

- {L(locale, "spell.see_overview", prefix=locale_prefix(locale))}
- {L(locale, "spell.see_reagents_li", prefix=locale_prefix(locale))}
"""
    return fm + body


def gen_index(spells: list, circles: dict, spell_icons: dict, locale: str) -> str:
    fm = frontmatter(
        L(locale, "magic.index_title"),
        L(locale, "magic.index_desc"),
        [
            "servuo: Scripts/Spells/Base/MagerySpell.cs",
            "servuo: Scripts/Spells/First..Eighth (spell registrations)",
        ],
    )
    out = [fm]
    out.append(L(locale, "magic.index_intro"))
    out += ["", f"## {L(locale, 'magic.circles')}", ""]
    out.append("| %s | %s | %s | %s |" % (
        L(locale, "col.circle"), L(locale, "col.mana"),
        L(locale, "magic.min_magery_0"), L(locale, "magic.magery_100")))
    out.append("| --- | --- | --- | --- |")
    for n in range(1, 9):
        ct = circles[str(n)]
        out.append(
            f"| {n} ({circle_word(locale, n)}) | {ct['mana']} | "
            f"{fmt_skill(ct['min_skill'])} | {fmt_skill(ct['max_skill'])} |"
        )
    out += ["", L(locale, "magic.skill_band_note"), ""]

    for n in range(1, 9):
        out.append("## " + L(locale, "magic.circle_heading", n=n, word=circle_word(locale, n)))
        out.append("")
        out.append("| | %s | %s | %s |" % (
            L(locale, "col.spell"), L(locale, "col.words_of_power"),
            L(locale, "col.reagents")))
        out.append("| --- | --- | --- | --- |")
        for spell_idx, s in enumerate(spells, 1):
            if s["circle"] != n:
                continue
            spell_id_str = str(spell_idx)
            icon_html = ""
            if spell_id_str in spell_icons.get("icons", {}):
                icon_html = f'<img src="/img/spells/{spell_id_str}.png" class="uo-sprite" alt="" width="44" height="44" />'
            out.append(f"| {icon_html} | {spell_link(s, locale)} | <span class=\"uo-ascii\">{s['mantra']}</span> | {', '.join(s['reagents'])} |")
        out.append("")

    out.append(L(locale, "magic.see_reagents", prefix=locale_prefix(locale)))
    out.append("")
    out.append(L(locale, "magic.runic_note"))
    out.append("")
    return "\n".join(out)


def gen_reagents(spells: list, locale: str) -> str:
    fm = frontmatter(
        L(locale, "reagents.title"),
        L(locale, "reagents.desc"),
        ["servuo: Scripts/Spells/Reagent.cs",
         "servuo: Scripts/Spells/First..Eighth (spell registrations)"],
    )
    out = [fm]
    out.append(L(locale, "reagents.intro"))
    out.append("")
    for reagent in REAGENT_SLUGS:
        users = [s for s in spells if reagent in s["reagents"]]
        # Reagent name heading stays English (proper noun); blurb is translated.
        out.append(f"## {reagent}")
        out.append("")
        out.append(L(locale, "reagblurb." + reagent))
        out.append("")
        out.append(L(locale, "reagents.used_by", n=len(users)))
        out.append("")
        for s in users:
            out.append(f"- {spell_link(s, locale)} ({L(locale, 'reagents.in_circle', n=s['circle'])})")
        out.append("")
    out.append(L(locale, "reagents.see_overview", prefix=locale_prefix(locale)))
    out.append("")
    return "\n".join(out)


def main():
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    spells, circles = data["spells"], data["circles"]
    spell_icons = json.loads(SPELL_ICONS_PATH.read_text(encoding="utf-8"))

    written = 0
    for locale in LOCALES:
        out = out_dir(locale)
        out.mkdir(parents=True, exist_ok=True)

        # Clean previously generated spell pages so renames don't leave orphans.
        for old in out.rglob("*.md"):
            if BANNER in old.read_text(encoding="utf-8"):
                old.unlink()

        (out / "index.md").write_text(
            gen_index(spells, circles, spell_icons, locale), encoding="utf-8")
        (out / "reagents.md").write_text(
            gen_reagents(spells, locale), encoding="utf-8")
        written += 2

        for spell_id, spell in enumerate(spells, 1):
            d = out / f"circle-{spell['circle']}"
            d.mkdir(exist_ok=True)
            (d / f"{spell['slug']}.md").write_text(
                gen_spell_page(spell, spell_id, circles, spell_icons, locale),
                encoding="utf-8")
            written += 1

    print(f"Wrote {written} pages under {DOCS_ROOT}")


if __name__ == "__main__":
    main()
