#!/usr/bin/env python3
"""Generate src/content/docs/crafting/ pages from data/recipes.json.

Produces crafting/index.md (overview) plus one page per craft system with
recipes in markdown tables grouped by category. All pages are marked
`generated: true` — never hand-edit them; fix tools/extract_crafting.py
or the source data and regenerate.

Usage: python3 tools/gen_crafting.py
"""

import datetime
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(ROOT, "data", "recipes.json")
OUT_DIR = os.path.join(ROOT, "src", "content", "docs", "crafting")

BANNER = ("<!-- AUTO-GENERATED by tools/gen_crafting.py from data/recipes.json"
          " — do not hand-edit -->")

TODAY = datetime.date.today().isoformat()


def md_escape(s):
    """Make a string safe inside a markdown table cell (and for Starlight)."""
    return (s.replace("|", "\\|")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
             .replace("{", "&#123;")
             .replace("}", "&#125;")
             .replace("\n", " "))


def frontmatter(title, description, sources):
    lines = [
        "---",
        "title: %s" % json.dumps(title),
        "description: %s" % json.dumps(description),
        "status: source-verified",
        "generated: true",
        "sources:",
    ]
    lines += ['  - "%s"' % s for s in sources]
    lines += ["last_verified: %s" % TODAY, "---", "", BANNER, ""]
    return "\n".join(lines)


def skill_cell(recipe, main_skill):
    parts = ["%.1f – %.1f" % (recipe["min_skill"], recipe["max_skill"])]
    if recipe.get("craft_skill") and recipe["craft_skill"] != main_skill:
        parts[0] = "%s %s" % (recipe["craft_skill"], parts[0])
    for sk in recipe.get("skills", []):
        parts.append("%s %.1f – %.1f" % (sk["skill"], sk["min"], sk["max"]))
    return "; ".join(parts)


def materials_cell(recipe):
    parts = []
    for res in recipe["resources"]:
        name = res["name"] or res["type"]
        if name.startswith("cliloc:"):
            name = res["type"]
        parts.append("%d %s" % (res["amount"], md_escape(name)))
    return ", ".join(parts)


def gen_system_page(slug, sysdata):
    system = sysdata["system"]
    main_skill = sysdata["main_skill"]
    recipes = sysdata["recipes"]

    # group by category, preserving source order
    categories = {}
    for r in recipes:
        categories.setdefault(r["category"], []).append(r)

    desc = ("All %d %s recipes (%s skill): skill ranges and material "
            "requirements, extracted from ServUO." %
            (len(recipes), system, main_skill))
    out = [frontmatter(system, desc, ["servuo: " + sysdata["source"]])]
    out.append("**Main skill:** %s · **Recipes:** %d\n" % (main_skill, len(recipes)))
    out.append("Skill range is the span from 0% success chance (min) to "
               "100% success chance (max).\n")

    for cat, items in categories.items():
        out.append("## %s\n" % md_escape(cat.title() if cat.islower() else cat))
        out.append("| Item | Skill | Materials |")
        out.append("| --- | --- | --- |")
        for r in items:
            name = r["name"] or r["item_type"]
            if name.startswith("cliloc:"):
                name = r["item_type"]
            out.append("| %s | %s | %s |" % (
                md_escape(name), skill_cell(r, main_skill), materials_cell(r)))
        out.append("")

    path = os.path.join(OUT_DIR, slug + ".md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out).rstrip() + "\n")
    return path


def gen_index(systems):
    desc = ("Overview of all %d craft systems on the shard, with recipe "
            "counts extracted from ServUO." % len(systems))
    sources = ["servuo: " + s["source"] for _, s in systems]
    out = [frontmatter("Crafting", desc, sources)]
    total = sum(len(s["recipes"]) for _, s in systems)
    out.append("The shard has **%d craft systems** with **%d craftable "
               "recipes**, extracted directly from the ServUO craft system "
               "definitions. Each page lists every recipe with its skill "
               "range and material costs.\n" % (len(systems), total))
    out.append("| Craft system | Main skill | Recipes |")
    out.append("| --- | --- | --- |")
    for slug, s in systems:
        out.append("| [%s](/crafting/%s/) | %s | %d |" % (
            s["system"], slug, s["main_skill"], len(s["recipes"])))
    out.append("")

    path = os.path.join(OUT_DIR, "index.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out).rstrip() + "\n")
    return path


def main():
    with open(DATA_PATH, encoding="utf-8") as f:
        data = json.load(f)

    systems = [(slug, s) for slug, s in data.items() if slug != "_schema"]
    systems.sort(key=lambda kv: kv[0])

    os.makedirs(OUT_DIR, exist_ok=True)
    for slug, s in systems:
        path = gen_system_page(slug, s)
        print("wrote %s (%d recipes)" % (os.path.relpath(path, ROOT),
                                         len(s["recipes"])))
    path = gen_index(systems)
    print("wrote %s" % os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
