#!/usr/bin/env python3
"""Generate the item catalog under src/content/docs/items/catalog/ from
data/items.json, classified by GAMEPLAY TYPE.

Items are reclassified from their ServUO source directory into gameplay
categories (Weapons by family, Armor by material, Shields, Jewelry,
Clothing, etc.) using the `base_type` field (the first classifier base
class in each item's ancestor chain) first, and the source `category` as a
fallback. So an Artifact katana lands in Weapons > Swords, not Artifacts.

Produces:
  catalog/index.md         — overview table of gameplay categories + links
  catalog/<slug>.md        — one page per gameplay category, grouped by
                             subcategory, each group an
                             Icon | Name | Item ID | Weight table.

All generated pages carry `generated: true` and the AUTO-GENERATED banner;
never hand-edit them — fix tools/extract_items.py / gen_items.py or the
source data and regenerate. Every banner-marked file in catalog/ is deleted
before regeneration so no stale source-dir pages remain.

Usage: python3 tools/gen_items.py
"""

import datetime
import json
import os
import re
import sys
from collections import OrderedDict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from i18n_labels import LOCALES, L, SKILL, locale_prefix  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(ROOT, "data", "items.json")
EXPANSION_PATH = os.path.join(ROOT, "data", "item_expansion.json")
DOCS_ROOT = os.path.join(ROOT, "src", "content", "docs")


def out_dir(locale):
    base = DOCS_ROOT if locale == "en" else os.path.join(DOCS_ROOT, locale)
    return os.path.join(base, "items", "catalog")


def cat_label(locale, category):
    """Localized gameplay-category name (English fallback via the key system)."""
    return L(locale, "cat." + category)


def cat_blurb(locale, category):
    return L(locale, "blurb." + category)


# Subcategories that have a glossary/generic translation; weapon families and
# other proper-noun-ish material names stay English (no label key → English).
def sub_label(locale, sub):
    if sub is None:
        return None
    try:
        return L(locale, "isub." + sub)
    except KeyError:
        return sub

BANNER = ("<!-- AUTO-GENERATED by tools/gen_items.py from data/items.json"
          " — do not hand-edit -->")
TODAY = datetime.date.today().isoformat()

# Gameplay category -> sidebar order. Drives both the per-page sidebar order
# and the order categories appear in the index overview.
CATEGORY_ORDER = OrderedDict([
    ("Weapons", 1),
    ("Armor", 2),
    ("Shields", 3),
    ("Jewelry", 4),
    ("Clothing", 5),
    ("Instruments", 6),
    ("Spellbooks & Talismans", 7),
    ("Potions", 8),
    ("Scrolls", 9),
    ("Reagents", 10),
    ("Food & Drink", 11),
    ("Resources", 12),
    ("Tools", 13),
    ("Lighting", 14),
    ("Containers", 15),
    ("Books", 16),
    ("Decorations", 17),
    ("Addons & Furniture", 18),
    ("Artifacts", 19),
    ("Functional", 20),
    ("Quest Items", 21),
    ("Miscellaneous", 22),
])

# Per-category one-line descriptions for frontmatter / page intro.
CATEGORY_BLURB = {
    "Weapons": "melee, ranged and thrown weapons grouped by family and the "
               "combat skill they train",
    "Armor": "wearable armor grouped by material, from cloth to dragon scale",
    "Shields": "shields of every material",
    "Jewelry": "rings, bracelets, necklaces and earrings",
    "Clothing": "non-armor wearables — hats, robes, footwear and more",
    "Instruments": "musical instruments used by the Musicianship skill",
    "Spellbooks & Talismans": "spellbooks, runebooks and talismans",
    "Potions": "drinkable and thrown potions",
    "Scrolls": "spell and skill scrolls",
    "Reagents": "spell-casting reagents",
    "Food & Drink": "food, ingredients and beverages",
    "Resources": "raw crafting materials — ingots, ore, wood, leather and hides",
    "Tools": "crafting and harvesting tools",
    "Lighting": "lanterns, torches, candles and lamps",
    "Containers": "chests, bags, boxes and other containers",
    "Books": "readable books",
    "Decorations": "statues, plants and decorative furnishings",
    "Addons & Furniture": "multi-tile house deco and crafting stations",
    "Artifacts": "rare and event-reward items not covered by another family",
    "Functional": "interactive functional items",
    "Quest Items": "items tied to quests",
    "Miscellaneous": "everything else",
}

# Training skill shown in weapon subcategory headings.
WEAPON_SUBCATS = {
    "Swords": "Swordsmanship",
    "Axes": "Swordsmanship",
    "Polearms": "Swordsmanship",
    "Maces & Hammers": "Mace Fighting",
    "Staves": "Mace Fighting",
    "Daggers & Knives": "Fencing",
    "Spears & Forks": "Fencing",
    "Bows & Crossbows": "Archery",
    "Thrown": "Throwing",
    "Wands": "Magery",
    "Other Weapons": None,
}


def slugify(name):
    s = name.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "misc"


def md_escape(s):
    """Make a string safe inside a markdown table cell (and for Starlight)."""
    return (str(s).replace("\\", "\\\\")
                  .replace("|", "\\|")
                  .replace("<", "&lt;")
                  .replace(">", "&gt;")
                  .replace("{", "&#123;")
                  .replace("}", "&#125;")
                  .replace("\n", " ")
                  .strip())


# --------------------------------------------------------------------------
# Classifier: item -> (gameplay_category, subcategory)
# --------------------------------------------------------------------------

WEAPON_BASE_SUBCAT = {
    "BaseSword": "Swords",
    "BaseAxe": "Axes",
    "BasePoleArm": "Polearms",
    "BaseBashing": "Maces & Hammers",
    "BaseStaff": "Staves",
    "BaseKnife": "Daggers & Knives",
    "BaseSpear": "Spears & Forks",
    "BaseRanged": "Bows & Crossbows",
    "BaseThrown": "Thrown",
    "BaseWand": "Wands",
}


def _contains(name, *subs):
    low = name.lower()
    return any(s.lower() in low for s in subs)


def armor_subcat(cls):
    """First matching material substring on the class name -> subcategory."""
    checks = [
        (("Gargish",), "Gargish"),
        (("Dragon",), "Dragon Scale"),
        (("Bone",), "Bone"),
        (("Leaf", "Woodland"), "Woodland"),
        (("Studded",), "Studded"),
        (("Ring",), "Ring Mail"),
        (("Chain",), "Chain Mail"),
        (("Plate",), "Plate"),
        (("Hide", "Tiger"), "Hide"),
        (("Leather",), "Leather"),
        (("Cloth",), "Cloth"),
        (("Helm", "Bascinet", "Circlet", "Kabuto", "Jingasa", "Cowl", "Hood"),
         "Helms"),
    ]
    for subs, sub in checks:
        if _contains(cls, *subs):
            return sub
    return "Other"


def jewelry_subcat(cls):
    if _contains(cls, "Ring"):
        return "Rings"
    if _contains(cls, "Bracelet"):
        return "Bracelets"
    if _contains(cls, "Necklace", "Amulet"):
        return "Necklaces"
    if _contains(cls, "Earrings"):
        return "Earrings"
    return "Other"


def clothing_subcat(cls, bt):
    if bt == "BaseHat" or _contains(cls, "Hat", "Cap", "Bonnet", "Hood"):
        return "Hats"
    if bt == "BaseShoes" or _contains(cls, "Boots", "Sandals", "Shoes"):
        return "Footwear"
    if _contains(cls, "Robe", "Cloak", "Cape"):
        return "Robes & Cloaks"
    if _contains(cls, "Pants", "Kilt", "Skirt", "Legs", "Shorts"):
        return "Pants & Skirts"
    if _contains(cls, "Shirt", "Tunic", "Doublet", "Surcoat", "Bustier"):
        return "Shirts & Tops"
    return "Other"


def resource_subcat(bt):
    if bt == "BaseIngot":
        return "Ingots"
    if bt == "BaseOre":
        return "Ore"
    if bt in ("BaseLog", "BaseBoard"):
        return "Wood"
    if bt in ("BaseLeather", "BaseHides"):
        return "Leather & Hides"
    return "Other"


def classify(it):
    """Return (gameplay_category, subcategory) for an item.

    base_type drives the classification; the source `category` is used only
    as a fallback for items with no classifier base_type.
    """
    bt = it.get("base_type")
    cls = it["class"]
    src = it.get("category") or ""

    # WEAPONS -------------------------------------------------------------
    if bt in WEAPON_BASE_SUBCAT:
        return "Weapons", WEAPON_BASE_SUBCAT[bt]
    if bt in ("BaseMeleeWeapon", "BaseWeapon"):
        return "Weapons", "Other Weapons"

    # SHIELDS -------------------------------------------------------------
    if bt == "BaseShield":
        return "Shields", None

    # ARMOR ---------------------------------------------------------------
    if bt == "BaseArmor":
        return "Armor", armor_subcat(cls)

    # JEWELRY -------------------------------------------------------------
    if bt == "BaseJewel":
        return "Jewelry", jewelry_subcat(cls)

    # SPELLCASTING --------------------------------------------------------
    if bt == "Spellbook":
        return "Spellbooks & Talismans", "Spellbooks"
    if bt == "Runebook":
        return "Spellbooks & Talismans", "Runebooks"
    if bt == "BaseTalisman":
        return "Spellbooks & Talismans", "Talismans"

    # INSTRUMENTS ---------------------------------------------------------
    if bt == "BaseInstrument":
        return "Instruments", None

    # CLOTHING ------------------------------------------------------------
    if bt in ("BaseClothing", "BaseHat", "BaseShoes"):
        return "Clothing", clothing_subcat(cls, bt)

    # POTIONS -------------------------------------------------------------
    if bt == "BasePotion":
        return "Potions", None

    # FOOD & DRINK --------------------------------------------------------
    if bt in ("Food", "BaseBeverage"):
        return "Food & Drink", None

    # REAGENTS ------------------------------------------------------------
    if bt == "BaseReagent":
        return "Reagents", None

    # RESOURCES (by base_type) -------------------------------------------
    if bt in ("BaseIngot", "BaseOre", "BaseLog", "BaseBoard",
              "BaseLeather", "BaseHides"):
        return "Resources", resource_subcat(bt)

    # SCROLLS -------------------------------------------------------------
    if cls.endswith("Scroll") or "Scroll" in cls:
        return "Scrolls", None

    # TOOLS ---------------------------------------------------------------
    if bt == "BaseTool" or src == "Tools":
        return "Tools", None

    # CONTAINERS ----------------------------------------------------------
    if bt == "BaseContainer" or src == "Containers":
        return "Containers", None

    # LIGHTING ------------------------------------------------------------
    if bt == "BaseLight" or _contains(cls, "Lantern", "Torch", "Candle", "Lamp"):
        return "Lighting", None

    # BOOKS ---------------------------------------------------------------
    if bt == "BaseBook" or src == "Books":
        return "Books", None

    # RESOURCES (source fallback) ----------------------------------------
    if src == "Resource":
        return "Resources", resource_subcat(bt)

    # FALLBACK by source category ----------------------------------------
    fallback = {
        "Decorative": ("Decorations", None),
        "Addons": ("Addons & Furniture", None),
        "Quest": ("Quest Items", None),
        "Artifacts": ("Artifacts", None),
        "Functional": ("Functional", None),
        "StoreBought": ("Miscellaneous", None),
    }
    if src in fallback:
        return fallback[src]
    return "Miscellaneous", None


# --------------------------------------------------------------------------
# Page rendering
# --------------------------------------------------------------------------

def frontmatter(title, description, sources, order):
    lines = [
        "---",
        "title: %s" % json.dumps(title),
        "description: %s" % json.dumps(description),
        "status: source-verified",
        "generated: true",
        "sidebar:",
        "  order: %d" % order,
        "sources:",
    ]
    lines += ['  - "%s"' % s for s in sources]
    lines += ["last_verified: %s" % TODAY, "---", "", BANNER, ""]
    return "\n".join(lines)


def icon_cell(png):
    if not png:
        return ""
    return ('<img src="%s" class="uo-sprite" alt="" width="48" '
            'loading="lazy" />' % png)


def weight_cell(weight):
    if weight is None:
        return "—"
    if isinstance(weight, float) and weight == int(weight):
        weight = int(weight)
    return str(weight)


def clean_generated(out_dir):
    """Delete every banner-marked .md file in out_dir (incl. old source-dir
    pages) so no stale catalog pages remain."""
    if not os.path.isdir(out_dir):
        return 0
    removed = 0
    for fn in os.listdir(out_dir):
        if not fn.endswith(".md"):
            continue
        p = os.path.join(out_dir, fn)
        try:
            text = open(p, encoding="utf-8").read()
        except OSError:
            continue
        if "AUTO-GENERATED" in text:
            os.remove(p)
            removed += 1
    return removed


def subcat_sort_key(category):
    """Ordering for subcategory headings within a category page."""
    if category == "Weapons":
        order = list(WEAPON_SUBCATS.keys())
        return lambda s: (order.index(s) if s in order else len(order), s.lower())
    if category == "Armor":
        order = ["Cloth", "Leather", "Studded", "Hide", "Bone", "Ring Mail",
                 "Chain Mail", "Plate", "Dragon Scale", "Woodland", "Gargish",
                 "Helms", "Other"]
        return lambda s: (order.index(s) if s in order else len(order), s.lower())
    if category == "Resources":
        order = ["Ingots", "Ore", "Wood", "Leather & Hides", "Other"]
        return lambda s: (order.index(s) if s in order else len(order), s.lower())
    return lambda s: (0, s.lower())


def heading_for(category, sub, locale):
    """Subcategory ## heading text (weapons show their training skill).

    Subcategory name is localized where a glossary/generic term exists, else
    kept English (weapon families, armor materials). The weapon training skill
    uses its official localized name."""
    label = sub_label(locale, sub)
    if category == "Weapons":
        skill = WEAPON_SUBCATS.get(sub)
        if skill:
            return "%s  ·  %s" % (md_escape(label), md_escape(SKILL(locale, skill)))
    return md_escape(label)


# Expansion timeline — items are grouped under these in chronological order, so
# Classic items come first, then each later expansion. Untagged items (era not
# determinable from the source) fall into a final section.
ERA_ORDER = ["Classic", "AOS", "SE", "ML", "SA", "HS", "TOL", "EJ"]
ERA_NAMES = {
    "Classic": "Classic (The Second Age era)",
    "AOS": "Age of Shadows (AOS)",
    "SE": "Samurai Empire (SE)",
    "ML": "Mondain's Legacy (ML)",
    "SA": "Stygian Abyss (SA)",
    "HS": "High Seas (HS)",
    "TOL": "Time of Legends (TOL)",
    "EJ": "Endless Journey (EJ)",
}
ERA_UNTAGGED = "Era not determined"


def _table(out, rows, locale):
    out.append("| %s | %s | %s | %s |" % (
        L(locale, "col.icon"), L(locale, "col.name"),
        L(locale, "col.item_id"), L(locale, "col.weight")))
    out.append("|------|------|---------|--------|")
    for it in rows:
        # Item names are proper nouns — kept English. ID/weight unchanged.
        out.append("| %s | %s | `%s` | %s |" % (
            icon_cell(it["png"]), md_escape(it["name"]),
            it["item_id"], weight_cell(it["weight"])))
    out.append("")


def _write_subcats(out, category, rows, heading_level, locale):
    """Emit rows grouped by subcategory under the given heading level (## or ###)."""
    groups = {}
    for it in rows:
        groups.setdefault(it["subcategory"] or "All", []).append(it)
    keys = sorted(groups.keys(), key=subcat_sort_key(category))
    single = len(keys) == 1 and keys[0] == "All"
    for sub in keys:
        if not single:
            out.append("%s %s\n" % (heading_level, heading_for(category, sub, locale)))
        _table(out, groups[sub], locale)


def write_category_page(out_dir_path, category, items, locale):
    slug = slugify(category)
    order = CATEGORY_ORDER[category]

    blurb = cat_blurb(locale, category)
    cat_name = cat_label(locale, category)
    title = cat_name
    description = L(locale, "items.cat_desc",
                   category=cat_name, n=len(items), blurb=blurb)
    sources = ["servuo: Scripts/Items", "servuo: Scripts/Services/Craft (eras)",
               "client: artLegacyMUL.uop"]

    out = [frontmatter(title, description, sources, order)]
    out.append(L(locale, "items.cat_intro",
                 category=cat_name, blurb=blurb, n=len(items)) + "\n")

    # Bucket by era; only craftable items carry one, the rest go to "untagged".
    by_era = {}
    for it in items:
        by_era.setdefault(it.get("era") or ERA_UNTAGGED, []).append(it)

    untagged_label = L(locale, "items.era_untagged")
    has_any_era = any(e in by_era for e in ERA_ORDER)
    if not has_any_era:
        # Nothing in this category is era-tagged — just group by subcategory.
        _write_subcats(out, category, items, "##", locale)
    else:
        # Era headings keep the English expansion label (proper-noun abbrev).
        for era in ERA_ORDER:
            if era not in by_era:
                continue
            rows = by_era[era]
            out.append("## %s  *(%d)*\n" % (md_escape(ERA_NAMES[era]), len(rows)))
            _write_subcats(out, category, rows, "###", locale)
        if ERA_UNTAGGED in by_era:
            rows = by_era[ERA_UNTAGGED]
            out.append("## %s  *(%d)*\n" % (md_escape(untagged_label), len(rows)))
            out.append(L(locale, "items.untagged_note") + "\n")
            _write_subcats(out, category, rows, "###", locale)

    with open(os.path.join(out_dir_path, "%s.md" % slug), "w") as f:
        f.write("\n".join(out).rstrip() + "\n")
    return slug


def write_index(out_dir_path, ordered_cats, cat_slugs, counts, total, locale):
    pfx = locale_prefix(locale)
    title = L(locale, "items.title")
    description = L(locale, "items.index_desc")
    sources = ["servuo: Scripts/Items", "client: artLegacyMUL.uop"]
    out = [frontmatter(title, description, sources, 0)]
    out.append(L(locale, "items.index_intro",
                 total=total, ncat=len(ordered_cats)) + "\n")
    out.append(L(locale, "items.index_regen") + "\n")
    out.append("| %s | %s |" % (L(locale, "col.category"), L(locale, "col.items")))
    out.append("|----------|-------|")
    for cat in ordered_cats:
        out.append("| [%s](%s/items/catalog/%s/) | %d |"
                   % (md_escape(cat_label(locale, cat)), pfx, cat_slugs[cat], counts[cat]))
    out.append("| **%s** | **%d** |" % (L(locale, "col.total"), total))
    out.append("")
    with open(os.path.join(out_dir_path, "index.md"), "w") as f:
        f.write("\n".join(out).rstrip() + "\n")


def main():
    doc = json.load(open(DATA_PATH))
    items = doc["items"]

    # Overlay expansion-introduction era (by item class) from
    # item_expansion.json. Only craftable classes are present there; items
    # with no entry simply have no era (blank cell / no Era column).
    expansion = json.load(open(EXPANSION_PATH)).get("by_class", {})
    for it in items:
        era = expansion.get(it.get("class"))
        if era:
            it["era"] = era

    # Classify every item into a gameplay (category, subcategory).
    cat_items = {}
    for it in items:
        cat, sub = classify(it)
        it = dict(it)
        it["subcategory"] = sub
        cat_items.setdefault(cat, []).append(it)

    # Sort items within each category by subcategory then name.
    for cat, rows in cat_items.items():
        rows.sort(key=lambda x: ((x["subcategory"] or "").lower(),
                                 x["name"].lower(), x["class"].lower()))

    # Emit pages in defined sidebar order; skip empty categories.
    ordered_cats = [c for c in CATEGORY_ORDER if cat_items.get(c)]

    for locale in LOCALES:
        out = out_dir(locale)
        os.makedirs(out, exist_ok=True)
        removed = clean_generated(out)
        if removed:
            print("[%s] removed %d stale generated page(s)" % (locale, removed))

        cat_slugs = {}
        counts = {}
        for cat in ordered_cats:
            rows = cat_items[cat]
            slug = write_category_page(out, cat, rows, locale)
            cat_slugs[cat] = slug
            counts[cat] = len(rows)

        write_index(out, ordered_cats, cat_slugs, counts, len(items), locale)
        print("[%s] wrote catalog/index.md + %d category pages (%d items total)"
              % (locale, len(cat_slugs), len(items)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
