# /// script
# requires-python = ">=3.11"
# ///
"""Generate the wiki's Recent Changes page from git history.

The wiki uses a commit convention (see CLAUDE.md): `wiki(<section>): <summary>
(<provenance>)` and `report(<agent>): <claim>`. This reads `git log`, parses
those, groups by date, and writes a reader- and agent-facing changelog at
src/content/docs/changelog.md — so anyone (including agents asking "what changed
since I last looked?") can see the wiki's history without reading git.

Regenerate it as part of shipping (LIBRARIAN.md step 7) or any time:
    python3 tools/gen_changelog.py

It is a generated page — never hand-edit it. Commits that only touch the
changelog itself are skipped so it doesn't echo its own updates.
"""

from __future__ import annotations

import datetime as dt
import re
import subprocess
from pathlib import Path

WIKI_ROOT = Path(__file__).resolve().parent.parent
OUT = WIKI_ROOT / "src" / "content" / "docs" / "changelog.md"
REL_OUT = OUT.relative_to(WIKI_ROOT).as_posix()

# Derive the GitHub commit URL base from the origin remote.
REMOTE = subprocess.run(
    ["git", "-C", str(WIKI_ROOT), "config", "--get", "remote.origin.url"],
    capture_output=True, text=True,
).stdout.strip()
COMMIT_BASE = ""
if REMOTE:
    slug = re.sub(r"\.git$", "", re.sub(r"^git@github\.com:", "", REMOTE))
    slug = re.sub(r"^https?://github\.com/", "", slug)
    if "/" in slug:
        COMMIT_BASE = f"https://github.com/{slug}/commit/"

MAX_COMMITS = 500
SEP = "\x1e"  # record separator unlikely to appear in a subject

# Friendly labels for the section badge in `wiki(<section>): ...`.
SECTION_LABELS = {
    "skills": "Skills", "magic": "Magic", "bestiary": "Bestiary",
    "items": "Items", "crafting": "Crafting", "world": "World",
    "mechanics": "Mechanics", "shard": "Shard", "guides": "Guides",
    "templates": "Templates", "assets": "Assets", "reports": "Reports",
    "mcp": "MCP", "meta": "Meta", "config": "Config",
}


def git_log() -> list[dict]:
    """Return commits (newest first) with the files each touched."""
    fmt = SEP.join(["%h", "%ad", "%s"])
    raw = subprocess.run(
        ["git", "-C", str(WIKI_ROOT), "log", f"-{MAX_COMMITS}",
         "--date=short", f"--pretty=format:__C__{fmt}", "--name-only"],
        capture_output=True, text=True, check=True,
    ).stdout
    commits: list[dict] = []
    for block in raw.split("__C__"):
        block = block.strip("\n")
        if not block:
            continue
        head, *rest = block.split("\n")
        parts = head.split(SEP)
        if len(parts) != 3:
            continue
        h, date, subject = parts
        files = [ln for ln in rest if ln.strip()]
        commits.append({"hash": h, "date": date, "subject": subject, "files": files})
    return commits


def parse_subject(subject: str) -> tuple[str | None, str]:
    """Split `wiki(section): summary` / `report(agent): claim` → (badge, text)."""
    m = re.match(r"^(\w+)\(([^)]+)\):\s*(.*)$", subject)
    if m:
        kind, scope, text = m.groups()
        if kind == "report":
            return f"report · {scope}", text
        return SECTION_LABELS.get(scope, scope), text
    m = re.match(r"^(\w+):\s*(.*)$", subject)
    if m:
        kind, text = m.groups()
        return SECTION_LABELS.get(kind, kind.capitalize()), text
    return None, subject


def md_escape(text: str) -> str:
    # Escape table/markdown-hostile chars; keep it light — these are prose summaries.
    return text.replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;")


def render(commits: list[dict]) -> str:
    today = dt.date.today().isoformat()
    lines = [
        "---",
        "title: Recent Changes",
        "description: A running log of edits to the wiki, generated from its git history — what was added, corrected, or verified, and when.",
        "status: source-verified",
        "sources:",
        '  - "git: commit history of this repository"',
        f"last_verified: {today}",
        "generated: true",
        "---",
        "",
        "<!-- AUTO-GENERATED by tools/gen_changelog.py from git history — do not hand-edit -->",
        "",
        "Every edit to this wiki is a git commit. This page is generated from that",
        "history so readers and agents can see what changed without reading the repo.",
        "Corrections driven by an in-game [discrepancy report](/guides/wiki-conventions/)",
        "or a ServUO source check are noted in the entry.",
        "",
    ]
    if COMMIT_BASE:
        lines.append(f"Full history: [{REMOTE_SLUG()}]({COMMIT_BASE.rsplit('/commit/', 1)[0]}/commits/).")
        lines.append("")

    # Group by date, preserving newest-first order.
    by_date: dict[str, list[dict]] = {}
    for c in commits:
        if c["files"] and all(f == REL_OUT for f in c["files"]):
            continue  # skip changelog-only commits
        by_date.setdefault(c["date"], []).append(c)

    for date in by_date:  # dict keeps insertion (newest-first) order
        lines.append(f"## {date}")
        lines.append("")
        for c in by_date[date]:
            badge, text = parse_subject(c["subject"])
            prefix = f"**{md_escape(badge)}** — " if badge else ""
            link = f" ([`{c['hash']}`]({COMMIT_BASE}{c['hash']}))" if COMMIT_BASE else f" (`{c['hash']}`)"
            lines.append(f"- {prefix}{md_escape(text)}{link}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def REMOTE_SLUG() -> str:
    return COMMIT_BASE.replace("https://github.com/", "").rsplit("/commit/", 1)[0]


def main() -> None:
    commits = git_log()
    OUT.write_text(render(commits), encoding="utf-8")
    shown = sum(1 for c in commits if not (c["files"] and all(f == REL_OUT for f in c["files"])))
    print(f"wrote {REL_OUT}: {shown} entries across "
          f"{len({c['date'] for c in commits})} day(s)")


if __name__ == "__main__":
    main()
