#!/usr/bin/env python3
"""Generate the item catalog under src/content/docs/items/catalog/ from
data/items.json, classified by GAMEPLAY TYPE.

Items are reclassified from their ServUO source directory into gameplay
categories (Weapons by family, Armor by material, Shields, Jewelry,
Clothing, etc.) using the `base_type` field (the first classifier base
class in each item's ancestor chain) first, and the source `category` as a
fallback. So an Artifact katana lands in Weapons > Swords, not Artifacts.

Produces:
  catalog/index.md         — overview table of gameplay categories + links
  catalog/<slug>.md        — one page per gameplay category, grouped by
                             subcategory, each group an
                             Icon | Name | Item ID | Weight table.

All generated pages carry `generated: true` and the AUTO-GENERATED banner;
never hand-edit them — fix tools/extract_items.py / gen_items.py or the
source data and regenerate. Every banner-marked file in catalog/ is deleted
before regeneration so no stale source-dir pages remain.

Usage: python3 tools/gen_items.py
"""

import datetime
import json
import os
import re
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(ROOT, "data", "items.json")
EXPANSION_PATH = os.path.join(ROOT, "data", "item_expansion.json")
OUT_DIR = os.path.join(ROOT, "src", "content", "docs", "items", "catalog")

BANNER = ("<!-- AUTO-GENERATED by tools/gen_items.py from data/items.json"
          " — do not hand-edit -->")
TODAY = datetime.date.today().isoformat()

# Gameplay category -> sidebar order. Drives both the per-page sidebar order
# and the order categories appear in the index overview.
CATEGORY_ORDER = OrderedDict([
    ("Weapons", 1),
    ("Armor", 2),
    ("Shields", 3),
    ("Jewelry", 4),
    ("Clothing", 5),
    ("Instruments", 6),
    ("Spellbooks & Talismans", 7),
    ("Potions", 8),
    ("Scrolls", 9),
    ("Reagents", 10),
    ("Food & Drink", 11),
    ("Resources", 12),
    ("Tools", 13),
    ("Lighting", 14),
    ("Containers", 15),
    ("Books", 16),
    ("Decorations", 17),
    ("Addons & Furniture", 18),
    ("Artifacts", 19),
    ("Functional", 20),
    ("Quest Items", 21),
    ("Miscellaneous", 22),
])

# Per-category one-line descriptions for frontmatter / page intro.
CATEGORY_BLURB = {
    "Weapons": "melee, ranged and thrown weapons grouped by family and the "
               "combat skill they train",
    "Armor": "wearable armor grouped by material, from cloth to dragon scale",
    "Shields": "shields of every material",
    "Jewelry": "rings, bracelets, necklaces and earrings",
    "Clothing": "non-armor wearables — hats, robes, footwear and more",
    "Instruments": "musical instruments used by the Musicianship skill",
    "Spellbooks & Talismans": "spellbooks, runebooks and talismans",
    "Potions": "drinkable and thrown potions",
    "Scrolls": "spell and skill scrolls",
    "Reagents": "spell-casting reagents",
    "Food & Drink": "food, ingredients and beverages",
    "Resources": "raw crafting materials — ingots, ore, wood, leather and hides",
    "Tools": "crafting and harvesting tools",
    "Lighting": "lanterns, torches, candles and lamps",
    "Containers": "chests, bags, boxes and other containers",
    "Books": "readable books",
    "Decorations": "statues, plants and decorative furnishings",
    "Addons & Furniture": "multi-tile house deco and crafting stations",
    "Artifacts": "rare and event-reward items not covered by another family",
    "Functional": "interactive functional items",
    "Quest Items": "items tied to quests",
    "Miscellaneous": "everything else",
}

# Training skill shown in weapon subcategory headings.
WEAPON_SUBCATS = {
    "Swords": "Swordsmanship",
    "Axes": "Swordsmanship",
    "Polearms": "Swordsmanship",
    "Maces & Hammers": "Mace Fighting",
    "Staves": "Mace Fighting",
    "Daggers & Knives": "Fencing",
    "Spears & Forks": "Fencing",
    "Bows & Crossbows": "Archery",
    "Thrown": "Throwing",
    "Wands": "Magery",
    "Other Weapons": None,
}


def slugify(name):
    s = name.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "misc"


def md_escape(s):
    """Make a string safe inside a markdown table cell (and for Starlight)."""
    return (str(s).replace("\\", "\\\\")
                  .replace("|", "\\|")
                  .replace("<", "&lt;")
                  .replace(">", "&gt;")
                  .replace("{", "&#123;")
                  .replace("}", "&#125;")
                  .replace("\n", " ")
                  .strip())


# --------------------------------------------------------------------------
# Classifier: item -> (gameplay_category, subcategory)
# --------------------------------------------------------------------------

WEAPON_BASE_SUBCAT = {
    "BaseSword": "Swords",
    "BaseAxe": "Axes",
    "BasePoleArm": "Polearms",
    "BaseBashing": "Maces & Hammers",
    "BaseStaff": "Staves",
    "BaseKnife": "Daggers & Knives",
    "BaseSpear": "Spears & Forks",
    "BaseRanged": "Bows & Crossbows",
    "BaseThrown": "Thrown",
    "BaseWand": "Wands",
}


def _contains(name, *subs):
    low = name.lower()
    return any(s.lower() in low for s in subs)


def armor_subcat(cls):
    """First matching material substring on the class name -> subcategory."""
    checks = [
        (("Gargish",), "Gargish"),
        (("Dragon",), "Dragon Scale"),
        (("Bone",), "Bone"),
        (("Leaf", "Woodland"), "Woodland"),
        (("Studded",), "Studded"),
        (("Ring",), "Ring Mail"),
        (("Chain",), "Chain Mail"),
        (("Plate",), "Plate"),
        (("Hide", "Tiger"), "Hide"),
        (("Leather",), "Leather"),
        (("Cloth",), "Cloth"),
        (("Helm", "Bascinet", "Circlet", "Kabuto", "Jingasa", "Cowl", "Hood"),
         "Helms"),
    ]
    for subs, sub in checks:
        if _contains(cls, *subs):
            return sub
    return "Other"


def jewelry_subcat(cls):
    if _contains(cls, "Ring"):
        return "Rings"
    if _contains(cls, "Bracelet"):
        return "Bracelets"
    if _contains(cls, "Necklace", "Amulet"):
        return "Necklaces"
    if _contains(cls, "Earrings"):
        return "Earrings"
    return "Other"


def clothing_subcat(cls, bt):
    if bt == "BaseHat" or _contains(cls, "Hat", "Cap", "Bonnet", "Hood"):
        return "Hats"
    if bt == "BaseShoes" or _contains(cls, "Boots", "Sandals", "Shoes"):
        return "Footwear"
    if _contains(cls, "Robe", "Cloak", "Cape"):
        return "Robes & Cloaks"
    if _contains(cls, "Pants", "Kilt", "Skirt", "Legs", "Shorts"):
        return "Pants & Skirts"
    if _contains(cls, "Shirt", "Tunic", "Doublet", "Surcoat", "Bustier"):
        return "Shirts & Tops"
    return "Other"


def resource_subcat(bt):
    if bt == "BaseIngot":
        return "Ingots"
    if bt == "BaseOre":
        return "Ore"
    if bt in ("BaseLog", "BaseBoard"):
        return "Wood"
    if bt in ("BaseLeather", "BaseHides"):
        return "Leather & Hides"
    return "Other"


def classify(it):
    """Return (gameplay_category, subcategory) for an item.

    base_type drives the classification; the source `category` is used only
    as a fallback for items with no classifier base_type.
    """
    bt = it.get("base_type")
    cls = it["class"]
    src = it.get("category") or ""

    # WEAPONS -------------------------------------------------------------
    if bt in WEAPON_BASE_SUBCAT:
        return "Weapons", WEAPON_BASE_SUBCAT[bt]
    if bt in ("BaseMeleeWeapon", "BaseWeapon"):
        return "Weapons", "Other Weapons"

    # SHIELDS -------------------------------------------------------------
    if bt == "BaseShield":
        return "Shields", None

    # ARMOR ---------------------------------------------------------------
    if bt == "BaseArmor":
        return "Armor", armor_subcat(cls)

    # JEWELRY -------------------------------------------------------------
    if bt == "BaseJewel":
        return "Jewelry", jewelry_subcat(cls)

    # SPELLCASTING --------------------------------------------------------
    if bt == "Spellbook":
        return "Spellbooks & Talismans", "Spellbooks"
    if bt == "Runebook":
        return "Spellbooks & Talismans", "Runebooks"
    if bt == "BaseTalisman":
        return "Spellbooks & Talismans", "Talismans"

    # INSTRUMENTS ---------------------------------------------------------
    if bt == "BaseInstrument":
        return "Instruments", None

    # CLOTHING ------------------------------------------------------------
    if bt in ("BaseClothing", "BaseHat", "BaseShoes"):
        return "Clothing", clothing_subcat(cls, bt)

    # POTIONS -------------------------------------------------------------
    if bt == "BasePotion":
        return "Potions", None

    # FOOD & DRINK --------------------------------------------------------
    if bt in ("Food", "BaseBeverage"):
        return "Food & Drink", None

    # REAGENTS ------------------------------------------------------------
    if bt == "BaseReagent":
        return "Reagents", None

    # RESOURCES (by base_type) -------------------------------------------
    if bt in ("BaseIngot", "BaseOre", "BaseLog", "BaseBoard",
              "BaseLeather", "BaseHides"):
        return "Resources", resource_subcat(bt)

    # SCROLLS -------------------------------------------------------------
    if cls.endswith("Scroll") or "Scroll" in cls:
        return "Scrolls", None

    # TOOLS ---------------------------------------------------------------
    if bt == "BaseTool" or src == "Tools":
        return "Tools", None

    # CONTAINERS ----------------------------------------------------------
    if bt == "BaseContainer" or src == "Containers":
        return "Containers", None

    # LIGHTING ------------------------------------------------------------
    if bt == "BaseLight" or _contains(cls, "Lantern", "Torch", "Candle", "Lamp"):
        return "Lighting", None

    # BOOKS ---------------------------------------------------------------
    if bt == "BaseBook" or src == "Books":
        return "Books", None

    # RESOURCES (source fallback) ----------------------------------------
    if src == "Resource":
        return "Resources", resource_subcat(bt)

    # FALLBACK by source category ----------------------------------------
    fallback = {
        "Decorative": ("Decorations", None),
        "Addons": ("Addons & Furniture", None),
        "Quest": ("Quest Items", None),
        "Artifacts": ("Artifacts", None),
        "Functional": ("Functional", None),
        "StoreBought": ("Miscellaneous", None),
    }
    if src in fallback:
        return fallback[src]
    return "Miscellaneous", None


# --------------------------------------------------------------------------
# Page rendering
# --------------------------------------------------------------------------

def frontmatter(title, description, sources, order):
    lines = [
        "---",
        "title: %s" % json.dumps(title),
        "description: %s" % json.dumps(description),
        "status: source-verified",
        "generated: true",
        "sidebar:",
        "  order: %d" % order,
        "sources:",
    ]
    lines += ['  - "%s"' % s for s in sources]
    lines += ["last_verified: %s" % TODAY, "---", "", BANNER, ""]
    return "\n".join(lines)


def icon_cell(png):
    if not png:
        return ""
    return ('<img src="%s" class="uo-sprite" alt="" width="48" '
            'loading="lazy" />' % png)


def weight_cell(weight):
    if weight is None:
        return "—"
    if isinstance(weight, float) and weight == int(weight):
        weight = int(weight)
    return str(weight)


def clean_generated(out_dir):
    """Delete every banner-marked .md file in out_dir (incl. old source-dir
    pages) so no stale catalog pages remain."""
    if not os.path.isdir(out_dir):
        return 0
    removed = 0
    for fn in os.listdir(out_dir):
        if not fn.endswith(".md"):
            continue
        p = os.path.join(out_dir, fn)
        try:
            text = open(p, encoding="utf-8").read()
        except OSError:
            continue
        if "AUTO-GENERATED" in text:
            os.remove(p)
            removed += 1
    return removed


def subcat_sort_key(category):
    """Ordering for subcategory headings within a category page."""
    if category == "Weapons":
        order = list(WEAPON_SUBCATS.keys())
        return lambda s: (order.index(s) if s in order else len(order), s.lower())
    if category == "Armor":
        order = ["Cloth", "Leather", "Studded", "Hide", "Bone", "Ring Mail",
                 "Chain Mail", "Plate", "Dragon Scale", "Woodland", "Gargish",
                 "Helms", "Other"]
        return lambda s: (order.index(s) if s in order else len(order), s.lower())
    if category == "Resources":
        order = ["Ingots", "Ore", "Wood", "Leather & Hides", "Other"]
        return lambda s: (order.index(s) if s in order else len(order), s.lower())
    return lambda s: (0, s.lower())


def heading_for(category, sub):
    """Subcategory ## heading text (weapons show their training skill)."""
    if category == "Weapons":
        skill = WEAPON_SUBCATS.get(sub)
        if skill:
            return "%s  ·  %s" % (md_escape(sub), md_escape(skill))
    return md_escape(sub)


def write_category_page(out_dir, category, items):
    slug = slugify(category)
    order = CATEGORY_ORDER[category]

    # group by subcategory
    groups = {}
    for it in items:
        sub = it["subcategory"] or "All"
        groups.setdefault(sub, []).append(it)
    sub_keys = sorted(groups.keys(), key=subcat_sort_key(category))

    # Include an Era column on this page only if at least one item has a
    # known expansion era. Kept consistent across all subcategory tables.
    show_era = any(it.get("era") for it in items)

    blurb = CATEGORY_BLURB.get(category, "items")
    title = category
    description = ("Every %s item in the ServUO source (%d) — %s — with art, "
                   "item IDs and weights." % (category, len(items), blurb))
    sources = ["servuo: Scripts/Items", "client: artLegacyMUL.uop"]

    out = [frontmatter(title, description, sources, order)]
    out.append("Auto-generated catalog of every %s — %s (%d items). Items are "
               "classified by gameplay type from the ServUO source; icons are "
               "static client art and item IDs are the resolved ServUO "
               "`ItemID`.\n" % (category, blurb, len(items)))

    single = len(sub_keys) == 1 and sub_keys[0] == "All"
    for sub in sub_keys:
        rows = groups[sub]
        if not single:
            out.append("## %s\n" % heading_for(category, sub))
        if show_era:
            out.append("| Icon | Name | Item ID | Weight | Era |")
            out.append("|------|------|---------|--------|-----|")
            for it in rows:
                out.append("| %s | %s | `%s` | %s | %s |" % (
                    icon_cell(it["png"]),
                    md_escape(it["name"]),
                    it["item_id"],
                    weight_cell(it["weight"]),
                    it.get("era") or "",
                ))
        else:
            out.append("| Icon | Name | Item ID | Weight |")
            out.append("|------|------|---------|--------|")
            for it in rows:
                out.append("| %s | %s | `%s` | %s |" % (
                    icon_cell(it["png"]),
                    md_escape(it["name"]),
                    it["item_id"],
                    weight_cell(it["weight"]),
                ))
        out.append("")

    with open(os.path.join(out_dir, "%s.md" % slug), "w") as f:
        f.write("\n".join(out).rstrip() + "\n")
    return slug


def write_index(out_dir, ordered_cats, cat_slugs, counts, total):
    title = "Item Catalog"
    description = ("Image-rich catalog of every item in the ServUO source, "
                   "grouped by gameplay type.")
    sources = ["servuo: Scripts/Items", "client: artLegacyMUL.uop"]
    out = [frontmatter(title, description, sources, 0)]
    out.append("A complete, auto-generated catalog of every concrete item "
               "class in the ServUO source — %d items across %d gameplay "
               "categories. Items are classified by gameplay type (weapons by "
               "family, armor by material, shields, jewelry, clothing, and so "
               "on) rather than by source directory. Each category page lists "
               "items with their client art, item ID and weight, grouped by "
               "subcategory.\n" % (total, len(ordered_cats)))
    out.append("This catalog is regenerated from `data/items.json` by "
               "`tools/gen_items.py`; do not hand-edit the category pages.\n")
    out.append("| Category | Items |")
    out.append("|----------|-------|")
    for cat in ordered_cats:
        out.append("| [%s](/items/catalog/%s/) | %d |"
                   % (md_escape(cat), cat_slugs[cat], counts[cat]))
    out.append("| **Total** | **%d** |" % total)
    out.append("")
    with open(os.path.join(out_dir, "index.md"), "w") as f:
        f.write("\n".join(out).rstrip() + "\n")


def main():
    doc = json.load(open(DATA_PATH))
    items = doc["items"]

    # Overlay expansion-introduction era (by item class) from
    # item_expansion.json. Only craftable classes are present there; items
    # with no entry simply have no era (blank cell / no Era column).
    expansion = json.load(open(EXPANSION_PATH)).get("by_class", {})
    for it in items:
        era = expansion.get(it.get("class"))
        if era:
            it["era"] = era

    os.makedirs(OUT_DIR, exist_ok=True)
    removed = clean_generated(OUT_DIR)
    if removed:
        print("removed %d stale generated page(s)" % removed)

    # Classify every item into a gameplay (category, subcategory).
    cat_items = {}
    for it in items:
        cat, sub = classify(it)
        it = dict(it)
        it["subcategory"] = sub
        cat_items.setdefault(cat, []).append(it)

    # Sort items within each category by subcategory then name.
    for cat, rows in cat_items.items():
        rows.sort(key=lambda x: ((x["subcategory"] or "").lower(),
                                 x["name"].lower(), x["class"].lower()))

    # Emit pages in defined sidebar order; skip empty categories.
    ordered_cats = [c for c in CATEGORY_ORDER if cat_items.get(c)]
    cat_slugs = {}
    counts = {}
    for cat in ordered_cats:
        rows = cat_items[cat]
        slug = write_category_page(OUT_DIR, cat, rows)
        cat_slugs[cat] = slug
        counts[cat] = len(rows)
        print("  %-24s -> catalog/%s.md (%d items)" % (cat, slug, len(rows)))

    write_index(OUT_DIR, ordered_cats, cat_slugs, counts, len(items))

    print("\nwrote catalog/index.md + %d category pages (%d items total)"
          % (len(cat_slugs), len(items)))
    print("sidebar order:")
    for cat in ordered_cats:
        print("  %2d  %-24s catalog/%s.md"
              % (CATEGORY_ORDER[cat], cat, cat_slugs[cat]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
