#!/usr/bin/env python3
"""Generate bestiary pages from data/creatures.json into src/content/docs/bestiary/.

One markdown page per creature, grouped into subdirectories (animals, monsters,
undead, elementals, humanoids, sea, bosses), plus an index page with group counts
and a notable-tamables table. All output is marked generated — never hand-edit;
fix tools/extract_creatures.py or this script and regenerate.

Usage: python3 tools/gen_bestiary.py
Stdlib only (Python 3.8+).
"""

import json
import os
import re
import shutil
import sys
from collections import OrderedDict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from i18n_labels import LOCALES, L, SKILL, locale_prefix  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(REPO_ROOT, "data", "creatures.json")
ANIM_PATH = os.path.join(REPO_ROOT, "data", "creature_anim.json")
DRESSED_PATH = os.path.join(REPO_ROOT, "data", "creature_dressed.json")
SOUNDS_PATH = os.path.join(REPO_ROOT, "data", "creature_sounds.json")
APPEARANCE_PATH = os.path.join(REPO_ROOT, "data", "mob_appearance.json")
DOCS_ROOT = os.path.join(REPO_ROOT, "src", "content", "docs")
OUT_DIR = os.path.join(DOCS_ROOT, "bestiary")


def out_dir(locale):
    base = DOCS_ROOT if locale == "en" else os.path.join(DOCS_ROOT, locale)
    return os.path.join(base, "bestiary")


def group_label(locale, gkey):
    return L(locale, "group." + gkey)


def bucket_label(locale, title):
    return L(locale, "bucket." + title)

BANNER = "<!-- AUTO-GENERATED by tools/gen_bestiary.py from data/creatures.json — do not hand-edit -->"
LAST_VERIFIED = "2026-06-11"

# Dressed (clothed/armed) walking GIFs keyed by creature class, from
# tools/extract_anim_dressed.py. Populated in main(); used to override the bare
# body sprite for humanoid mobs that wear equipment.
DRESSED = {}


def _creature_art(c, anim_data):
    """Resolve (gif, png, dressed) art paths for a creature.

    Prefers the dressed (clothed/armed) render when one exists; otherwise falls
    back to the bare-body GIF/PNG from creature_anim.json. Returns (gif, png,
    is_dressed) with None entries when no art exists."""
    cls = c["class"]
    dressed = DRESSED.get(cls)
    if dressed and dressed.get("gif"):
        return dressed.get("gif"), dressed.get("png"), True
    if anim_data and cls in anim_data.get("creatures", {}):
        body_id = anim_data["creatures"][cls]
        body = anim_data.get("bodies", {}).get(str(body_id))
        if body:
            return body.get("gif"), body.get("png"), False
    return None, None, False

GROUPS = OrderedDict([
    ("animals", "Animals"),
    ("monsters", "Monsters"),
    ("humanoids", "Humanoids"),
    ("undead", "Undead"),
    ("elementals", "Elementals"),
    ("sea", "Sea Creatures"),
    ("bosses", "Bosses & Champions"),
])

UNDEAD_KEYS = (
    "lich", "skelet", "zombie", "bone", "spectre", "specter", "ghost", "ghoul",
    "wraith", "mumm", "vampire", "shade", "rotting", "revenant", "deathknight",
    "bogle", "undead", "gore fiend", "gorefiend", "spectral",
)
SEA_KEYS = (
    "kraken", "leviathan", "dolphin", "seaserpent", "sea serpent", "squid",
    "charybdis", "osiredon", "scalis",
)
HUMANOID_KEYS = (
    "orc", "troll", "ogre", "ettin", "cyclop", "titan", "savage", "brigand",
    "pirate", "ratman", "lizardman", "juka", "meer", "minotaur", "gargoyle",
    "headless", "evil mage", "evilmage", "executioner", "barracoon", "harrower?",
    "mage lord", "berserker", "tribesman", "shaman", "champion of the", "kotl",
    "myrmidex?",  # insectoid, excluded via trailing '?'
)


def _match(keys, *texts):
    blob = " ".join(t.lower() for t in texts if t)
    return any(k in blob for k in keys if not k.endswith("?"))


# Sub-division of the (huge) Monsters group into typed buckets. Ordered: each
# creature lands in the FIRST bucket whose keywords match its class+name; the
# rest fall through to "Other Monsters". The goal is shorter sections, not a
# perfect taxonomy. ServUO doesn't tag creatures with an introduction era, so we
# group by kind instead.
MONSTER_BUCKETS = OrderedDict([
    ("Dragons & Wyrms", (
        "dragon", "wyrm", "drake", "wyvern", "hiryu", "reptalon", "serpentine dragon")),
    ("Daemons & Fiends", (
        "daemon", "demon", "imp", "balron", "succubus", "fiend", "devourer", "gargoyle")),
    ("Reptiles & Serpents", (
        "lizard", "snake", "serpent", "basilisk", "ophidian", "gator", "hydra", "coil",
        "reptile", "raptor", "dino", "saurian", "t-rex", "triceratops", "deinonych")),
    ("Beasts & Hounds", (
        "wolf", "hound", "hellcat", "hell hound", "ridgeback", "gaman", "beast",
        "panther", "lion", "tiger", "ravager")),
    ("Insects & Arachnids", (
        "spider", "scorpion", "beetle", "ant", "wasp", "mantis", "locust", "bee",
        "mephitis", "terathan", "moloch", "solen", "mite", "bloodworm", "worm",
        "abscess", "kepetch")),
    ("Magical & Fey", (
        "pixie", "fey", "satyr", "wisp", "unicorn", "kirin", "nightmare", "mare",
        "sprite", "faerie", "cu sidhe", "dryad", "changeling", "centaur", "efreet",
        "steed", "fire rabbit", "blade spirit", "vortex", "doppleganger")),
    ("Goblins & Gremlins", (
        "goblin", "gremlin", "gibberling", "mongbat", "minion")),
    ("Gazers & Aberrations", (
        "gazer", "corporeal", "brume", "horror", "abomination", "putrification",
        "essence", "fetid", "miasma", "maddening", "fleshrenderer", "lifestealer",
        "interred", "ilhenir", "grizzle")),
    ("Tokuno & Eastern", (
        "kitsune", "kappa", "kaze", "fan dancer", "ninja", "oni", "yamandon",
        "tsuki", "rune beetle", "deathwatch", "lady of the snow", "raiju")),
    ("Birds & Harpies", ("harpy", "phoenix", "bird", "raven", "crane", "stymphalian")),
    ("Slimes & Oozes", ("slime", "ooze", "jelly", "blob", "corrosive", "acid")),
    ("Plants & Fungi", (
        "reaper", "corpser", "plant", "mushroom", "shrub", "whipping", "bogling",
        "treefellow", "pumpkin")),
    ("Giants & Brutes", (
        "cyclops", "titan", "ogre", "ettin", "troll", "golem", "colossus", "brute",
        "juggernaut", "meraktus", "exodus", "construct", "automaton")),
    ("Other Monsters", ()),
])


def monster_bucket(c):
    """Return the bucket title for a monster, first-match wins."""
    name = c.get("name") or ""
    cls = c["class"]
    for title, keys in MONSTER_BUCKETS.items():
        if title == "Other Monsters":
            continue
        if _match(keys, cls, name):
            return title
    return "Other Monsters"


def classify(c):
    cls = c["class"]
    name = c.get("name") or ""
    src = c["source"]
    if "/Bosses/" in src:
        return "bosses"
    if _match(SEA_KEYS, cls, name):
        return "sea"
    if "elemental" in cls.lower() or "elemental" in name.lower():
        return "elementals"
    if _match(UNDEAD_KEYS, cls, name):
        return "undead"
    if _match(HUMANOID_KEYS, cls, name):
        return "humanoids"
    if c.get("ai_type") == "AI_Animal":
        return "animals"
    return "monsters"


def camel_to_words(s):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", " ", s)


def display_name(c):
    name = c.get("name")
    if name:
        name = re.sub(r"^(a|an|the)\s+", "", name.strip(), flags=re.I)
        return name.title() if name else camel_to_words(c["class"])
    return camel_to_words(c["class"])


def slug(c):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", "-", c["class"]).lower()


def fmt_range(v, dash="–"):
    if isinstance(v, list):
        return f"{v[0]}{dash}{v[1]}"
    return str(v)


def yaml_str(s):
    return json.dumps(s, ensure_ascii=False)


def describe(c):
    bits = []
    if "hits" in c:
        bits.append(f"hits {fmt_range(c['hits'])}")
    if "damage" in c:
        bits.append(f"damage {fmt_range(c['damage'])}")
    if "ai_type" in c:
        bits.append(c["ai_type"].replace("AI_", "") + " AI")
    desc = f"{display_name(c)} — " + ", ".join(bits) if bits else display_name(c)
    if c.get("tamable"):
        mts = c.get("min_tame_skill")
        desc += f"; tamable{f' at {mts} Animal Taming' if mts is not None else ''}"
    return desc + "."


# Layers treated as "wielded" (a weapon) vs "worn" for the prose.
WIELD_LAYERS = {"OneHanded", "TwoHanded"}


def _join_words(parts):
    """Oxford-free 'a, b and c' joiner for the appearance sentence."""
    parts = [p for p in parts if p]
    if not parts:
        return ""
    if len(parts) == 1:
        return parts[0]
    return ", ".join(parts[:-1]) + " and " + parts[-1]


def _item_phrase(w):
    """Lowercase item name with an article, noting dyed pieces.

    items.json names often already carry an article ('a bow', 'an orcish bow');
    strip it first so we don't double up, then re-derive based on the (possibly
    'dyed'-prefixed) noun."""
    name = (w.get("name") or camel_to_words(w["class"])).lower()
    name = re.sub(r"^(?:a|an|the)\s+", "", name)
    if w.get("hue_random"):
        name = "dyed " + name
    # plural-ish pieces (arms/legs/boots/pants/gloves) read better without article
    if re.search(r"(arms|legs|boots|pants|gloves|mitts|sandals|greaves)$", name):
        return name
    art = "an" if name[:1] in "aeiou" else "a"
    return f"{art} {name}"


def appearance_prose(worn):
    """One sentence: what the creature wears and wields, from the worn list."""
    worn_items = [w for w in worn if w.get("layer") not in WIELD_LAYERS]
    wield_items = [w for w in worn if w.get("layer") in WIELD_LAYERS]

    def group_phrases(items, collapse_optional=False):
        # Group optional alternatives into a single "one of: a, b, c" choice;
        # required pieces are listed plainly. When collapse_optional is set, ALL
        # optional pieces share one choice (a creature picks one weapon total,
        # even across the One/TwoHanded layers); otherwise they group by layer
        # (so a random shirt and a random hat stay distinct slots).
        by_layer_opt = {}
        order = []
        for w in items:
            if w.get("optional"):
                key = "_one" if collapse_optional else (w.get("layer") or w["class"])
                if key not in by_layer_opt:
                    by_layer_opt[key] = []
                    order.append(("opt", key))
                by_layer_opt[key].append(w)
            else:
                order.append(("req", w))
        phrases = []
        for kind, val in order:
            if kind == "req":
                phrases.append(_item_phrase(val))
            else:
                alts = by_layer_opt[val]
                if len(alts) == 1:
                    phrases.append("sometimes " + _item_phrase(alts[0]))
                else:
                    names = _join_words([_item_phrase(a) for a in alts])
                    phrases.append("one of: " + names)
        return phrases

    bits = []
    wp = group_phrases(worn_items)
    if wp:
        bits.append("Wears " + _join_words(wp))
    vp = group_phrases(wield_items, collapse_optional=True)
    if vp:
        verb = "wields " if bits else "Wields "
        bits.append(verb + _join_words(vp))
    if not bits:
        return ""
    return ", and ".join(bits).rstrip() + "."


def appearance_section(c, appearance, locale="en"):
    """Markdown lines for the ## Appearance section, or [] if not applicable.

    Note: the appearance *prose* (Wears…/Wields…) is generated from item names
    and stays English; only the section heading, table headers and notes are
    localized."""
    entry = appearance.get(c["class"]) if appearance else None
    if not entry or not entry.get("worn"):
        return []
    worn = entry["worn"]
    name = display_name(c)
    lines = [f"## {L(locale, 'sect.appearance')}", ""]
    prose = appearance_prose(worn)
    if prose:
        lines += [prose, ""]
    if entry.get("paperdoll"):
        lines += [
            f'<img src="{entry["paperdoll"]}" alt="{name} equipped" width="220" />',
            "",
        ]
    # Worn-item table: icon + name (+ optional/dyed note). Item names stay English.
    lines += [f"| | {L(locale, 'col.item')} | {L(locale, 'col.slot')} | |", "|---|---|---|---|"]
    for w in worn:
        icon = (f'<img src="{w["png"]}" class="uo-sprite" alt="" width="56" />'
                if w.get("png") else "")
        nm = w.get("name") or camel_to_words(w["class"])
        notes = []
        if w.get("optional"):
            notes.append(L(locale, "appearance.note.random"))
        if w.get("hue_random"):
            notes.append(L(locale, "appearance.note.dyed"))
        slotname = w.get("layer") or "—"
        note = ", ".join(notes)
        lines.append(f"| {icon} | {nm} | {slotname} | {note} |")
    lines += ["",
              L(locale, "appearance.paperdoll_ref", prefix=locale_prefix(locale)), ""]
    return lines


def creature_page(c, group, anim_data=None, sounds_data=None, appearance=None, locale="en"):
    name = display_name(c)
    lines = [
        "---",
        f"title: {yaml_str(name)}",
        f"description: {yaml_str(describe(c))}",
        "status: source-verified",
        "generated: true",
        # Keep the 562 individual creatures out of the left sidebar; only the
        # group index pages are listed there. (Starlight sidebar.hidden.)
        "sidebar:",
        "  hidden: true",
        "sources:",
        f"  - {yaml_str('servuo: ' + c['source'])}",
        f"last_verified: {LAST_VERIFIED}",
        "---",
        BANNER,
        "",
    ]

    # Add GIF if available (dressed render preferred over bare body).
    gif_path, _png, _dressed = _creature_art(c, anim_data)
    if gif_path:
        lines.append(f'<img src="{gif_path}" class="uo-anim" alt="{name} animation" />')
        lines.append("")

    facts = []
    if c.get("name"):
        facts.append((L(locale, "fact.in_game_name"), c["name"]))
    elif c.get("name_list"):
        facts.append((L(locale, "fact.in_game_name"),
                      L(locale, "fact.random_name", list=c["name_list"])))
    if c.get("corpse_name"):
        facts.append((L(locale, "fact.corpse"), c["corpse_name"]))
    if "body" in c:
        b = c["body"]
        facts.append((L(locale, "fact.body_id"), ", ".join(str(x) for x in b) if isinstance(b, list) else str(b)))
    if "base_sound_id" in c:
        facts.append((L(locale, "fact.base_sound_id"), str(c["base_sound_id"])))
    if "ai_type" in c:
        facts.append((L(locale, "fact.ai"), c["ai_type"]))
    if "fight_mode" in c:
        facts.append((L(locale, "fact.fight_mode"), c["fight_mode"]))
    if "fame" in c:
        facts.append((L(locale, "fact.fame"), str(c["fame"])))
    if "karma" in c:
        facts.append((L(locale, "fact.karma"), str(c["karma"])))
    if "virtual_armor" in c:
        facts.append((L(locale, "fact.virtual_armor"), str(c["virtual_armor"])))
    facts.append((L(locale, "fact.script"), f"`{c['source']}`"))
    lines += ["| | |", "|---|---|"]
    lines += [f"| **{k}** | {v} |" for k, v in facts]
    lines.append("")

    stat_rows = [(label, c[key]) for label, key in
                 ((L(locale, "row.strength"), "str"), (L(locale, "row.dexterity"), "dex"),
                  (L(locale, "row.intelligence"), "int"), (L(locale, "col.hits"), "hits"),
                  (L(locale, "row.stamina"), "stam"), (L(locale, "row.mana"), "mana"),
                  (L(locale, "col.damage"), "damage")) if key in c]
    if stat_rows:
        lines += [f"## {L(locale, 'sect.stats')}", "",
                  f"| {L(locale, 'col.stat')} | {L(locale, 'col.value')} |", "|---|---|"]
        lines += [f"| {label} | {fmt_range(v)} |" for label, v in stat_rows]
        if c.get("damage_types"):
            dt = ", ".join(f"{k} {v}%" for k, v in c["damage_types"].items())
            lines.append(f"| {L(locale, 'row.damage_type')} | {dt} |")
        lines.append("")

    if c.get("resistances"):
        lines += [f"## {L(locale, 'sect.resistances')}", "",
                  "| %s | %s | %s | %s | %s |" % (
                      L(locale, "res.physical"), L(locale, "res.fire"),
                      L(locale, "res.cold"), L(locale, "res.poison"),
                      L(locale, "res.energy")),
                  "|---|---|---|---|---|"]
        row = [fmt_range(c["resistances"].get(k, 0))
               for k in ("Physical", "Fire", "Cold", "Poison", "Energy")]
        lines += ["| " + " | ".join(row) + " |", ""]

    if c.get("skills"):
        lines += [f"## {L(locale, 'sect.skills')}", "",
                  f"| {L(locale, 'col.skill')} | {L(locale, 'col.value')} |", "|---|---|"]
        lines += [f"| {SKILL(locale, k)} | {fmt_range(v)} |" for k, v in sorted(c["skills"].items())]
        lines.append("")

    lines += appearance_section(c, appearance, locale)

    loot = c.get("loot") or {}
    res_rows = [(label, key, c[key]) for label, key in
                ((L(locale, "row.meat"), "meat"), (L(locale, "row.hides"), "hides"),
                 (L(locale, "row.feathers"), "feathers"), (L(locale, "row.wool"), "wool"))
                if key in c]
    if loot or res_rows:
        lines += [f"## {L(locale, 'sect.loot_resources')}", ""]
        if loot.get("packs"):
            lines += [f"| {L(locale, 'row.loot_pack')} | {L(locale, 'row.count')} |", "|---|---|"]
            lines += [f"| {p['pack']} | {p['count']} |" for p in loot["packs"]]
            lines.append("")
        if loot.get("pack_gold"):
            lines += ["- " + L(locale, "appearance.gold", v=fmt_range(loot['pack_gold']))]
        if loot.get("pack_items"):
            items = ", ".join(camel_to_words(i) for i in loot["pack_items"])
            lines += ["- " + L(locale, "appearance.pack_items", items=items)]
        if loot.get("pack_gold") or loot.get("pack_items"):
            lines.append("")
        if res_rows:
            hide_note = f" ({c['hide_type'].lower()})" if c.get("hide_type") else ""
            carve = ", ".join(
                f"{v} {label.lower()}{hide_note if key == 'hides' else ''}"
                for label, key, v in res_rows)
            lines += [L(locale, "appearance.carve", parts=carve), ""]

    if c.get("tamable"):
        lines += [f"## {L(locale, 'sect.taming')}", "", "| | |", "|---|---|"]
        if c.get("min_tame_skill") is not None:
            lines.append(f"| **{L(locale, 'taming.min_skill')}** | {c['min_tame_skill']} |")
        if c.get("control_slots") is not None:
            lines.append(f"| **{L(locale, 'taming.control_slots')}** | {c['control_slots']} |")
        lines.append("")

    # Add Sounds section if available
    if sounds_data and c["class"] in sounds_data["creatures"]:
        base_sound_id = sounds_data["creatures"][c["class"]]
        if str(base_sound_id) in sounds_data["sounds"]:
            sounds = sounds_data["sounds"][str(base_sound_id)]
            lines += [f"## {L(locale, 'sect.sounds')}", ""]
            for skey, src_key in (("sound.anger", "anger"), ("sound.idle", "idle"),
                                  ("sound.attack", "attack"), ("sound.hurt", "hurt"),
                                  ("sound.death", "death")):
                src = sounds[src_key]
                lines.append(f'**{L(locale, skey)}** <audio controls preload="none" src="{src}"></audio>')
                lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def index_page(grouped, creatures, anim_data=None, locale="en"):
    total = len(creatures)
    pfx = locale_prefix(locale)
    lines = [
        "---",
        # EN keeps the original bare-scalar title; localized titles are quoted
        # because they contain non-ASCII.
        ("title: Bestiary" if locale == "en"
         else f"title: {yaml_str(L(locale, 'bestiary.title'))}"),
        (f"description: Creature reference for our shard — {total} creatures extracted from ServUO source."
         if locale == "en"
         else f"description: {yaml_str(L(locale, 'bestiary.index_desc', n=total))}"),
        "status: source-verified",
        "generated: true",
        "sources:",
        '  - "servuo: Scripts/Mobiles/ (via tools/extract_creatures.py)"',
        f"last_verified: {LAST_VERIFIED}",
        "---",
        BANNER,
        "",
        L(locale, "bestiary.intro", n=total),
        "",
        f"## {L(locale, 'bestiary.groups')}",
        "",
        f"| | {L(locale, 'col.group')} | {L(locale, 'col.creatures')} |",
        "|---|---|---|",
    ]
    for gkey, gtitle in GROUPS.items():
        members = grouped.get(gkey, [])
        glabel = group_label(locale, gkey)
        # representative thumbnail: first member of this group that has a GIF.
        # The alt text is the (English) group title, matching the original.
        thumb = ""
        for c in sorted(members, key=display_name):
            t = _anim_thumb(c, anim_data, gtitle)
            if t:
                thumb = t
                break
        lines.append(f"| {thumb} | [{glabel}]({pfx}/bestiary/{gkey}/) | {len(members)} |")
    lines += ["", f"## {L(locale, 'bestiary.notable_tamables')}", "",
              L(locale, "bestiary.tamables_intro"), "",
              "| | %s | %s | %s | %s | %s |" % (
                  L(locale, "col.creature"), L(locale, "col.group"),
                  L(locale, "col.min_taming"), L(locale, "col.slots"),
                  L(locale, "col.hits")),
              "|---|---|---|---|---|---|"]
    tames = sorted(
        (c for c in creatures if c.get("tamable") and c.get("min_tame_skill") is not None),
        key=lambda c: -c["min_tame_skill"])[:20]
    for c in tames:
        g = classify(c)
        name = display_name(c)
        link = f"[{name}]({pfx}/bestiary/{g}/{slug(c)}/)"
        lines.append(f"| {_anim_thumb(c, anim_data, name)} | {link} | {group_label(locale, g)} | {c['min_tame_skill']} | "
                     f"{c.get('control_slots', '—')} | {fmt_range(c.get('hits', '—'))} |")
    lines += ["",
              L(locale, "bestiary.all_tamable",
                n=sum(1 for c in creatures if c.get('tamable'))), ""]
    return "\n".join(lines)


def _anim_thumb(c, anim_data, name):
    """A hover-swap thumbnail cell for a listing table, or empty if no art.

    Shows the static first-frame PNG by default and the animated GIF on hover
    (CSS in src/styles/sprites.css drives the swap). Falls back to the PNG alone
    if there's somehow no GIF, and to an empty cell if there's neither.
    """
    gif, png, _dressed = _creature_art(c, anim_data)
    if not gif and not png:
        return ""
    alt = name.replace('"', "&quot;")
    if png and gif:
        return (f'<span class="cthumb">'
                f'<img class="cthumb-png" src="{png}" alt="{alt}" loading="lazy" />'
                f'<img class="cthumb-gif" src="{gif}" alt="" loading="lazy" />'
                f'</span>')
    if png:
        return f'<img class="cthumb-png" src="{png}" alt="{alt}" loading="lazy" />'
    if gif:
        return f'<img src="{gif}" class="uo-anim" alt="{alt}" loading="lazy" />'
    return ""


# Groups bigger than this get sub-divided by type (Monsters is the main one).
SUBDIVIDE_THRESHOLD = 120


def _creature_table(members, gkey, anim_data, locale="en"):
    """Render the standard listing table (thumb + name + hits/damage/tamable)."""
    pfx = locale_prefix(locale)
    yes = L(locale, "cell.yes")
    lines = [
        "| | %s | %s | %s | %s |" % (
            L(locale, "col.creature"), L(locale, "col.hits"),
            L(locale, "col.damage"), L(locale, "col.tamable")),
        "|---|---|---|---|---|",
    ]
    for c in sorted(members, key=display_name):
        tame = f"{yes} ({c['min_tame_skill']})" if c.get("tamable") and c.get("min_tame_skill") is not None \
            else (yes if c.get("tamable") else "—")
        name = display_name(c)
        lines.append(f"| {_anim_thumb(c, anim_data, name)} | [{name}]({pfx}/bestiary/{gkey}/{slug(c)}/) "
                     f"| {fmt_range(c.get('hits', '—'))} | {fmt_range(c.get('damage', '—'))} | {tame} |")
    lines.append("")
    return lines


def group_index_page(gkey, gtitle, members, anim_data=None, locale="en"):
    glabel = group_label(locale, gkey)
    lines = [
        "---",
        f"title: {yaml_str(glabel)}",
        f"description: {yaml_str(L(locale, 'bestiary.group_desc', group=glabel, n=len(members)))}",
        "status: source-verified",
        "generated: true",
        "sources:",
        '  - "servuo: Scripts/Mobiles/ (via tools/extract_creatures.py)"',
        '  - "client: anim*.mul (via tools/extract_anim.py)"',
        f"last_verified: {LAST_VERIFIED}",
        "---",
        BANNER,
        "",
    ]

    # Sub-divide oversized groups (Monsters, ~340) into typed sections so no
    # single table is unmanageably long. Smaller groups stay one flat table.
    if gkey == "monsters" or len(members) > SUBDIVIDE_THRESHOLD:
        buckets = OrderedDict((title, []) for title in MONSTER_BUCKETS)
        for c in members:
            buckets[monster_bucket(c)].append(c)
        lines += [
            L(locale, "bestiary.grouped_by_type"),
            "",
        ]
        for title, group_members in buckets.items():
            if not group_members:
                continue
            lines.append(f"## {bucket_label(locale, title)}  *({len(group_members)})*")
            lines.append("")
            lines += _creature_table(group_members, gkey, anim_data, locale)
        return "\n".join(lines)

    lines += _creature_table(members, gkey, anim_data, locale)
    return "\n".join(lines)


def main():
    with open(DATA_PATH, encoding="utf-8") as f:
        data = json.load(f)
    creatures = data["creatures"]

    # Load animation and sound data
    with open(ANIM_PATH, encoding="utf-8") as f:
        anim_data = json.load(f)
    # Dressed (clothed/armed) renders, when present, override the bare body art.
    global DRESSED
    if os.path.exists(DRESSED_PATH):
        with open(DRESSED_PATH, encoding="utf-8") as f:
            DRESSED = json.load(f).get("creatures", {})
    with open(SOUNDS_PATH, encoding="utf-8") as f:
        sounds_data = json.load(f)
    appearance = {}
    if os.path.exists(APPEARANCE_PATH):
        with open(APPEARANCE_PATH, encoding="utf-8") as f:
            appearance = json.load(f).get("creatures", {})

    grouped = {}
    for c in creatures:
        grouped.setdefault(classify(c), []).append(c)

    for locale in LOCALES:
        base = out_dir(locale)
        # Remove previously generated output (everything under bestiary/ is owned
        # by this script; only files carrying the banner are deleted, as a safety
        # net).
        if os.path.isdir(base):
            for dirpath, _dirs, files in os.walk(base, topdown=False):
                for fn in files:
                    p = os.path.join(dirpath, fn)
                    if fn.endswith((".md", ".mdx")):
                        with open(p, encoding="utf-8") as f:
                            if BANNER in f.read():
                                os.remove(p)
                if dirpath != base and not os.listdir(dirpath):
                    shutil.rmtree(dirpath)

        pages = 0
        for gkey, members in grouped.items():
            gdir = os.path.join(base, gkey)
            os.makedirs(gdir, exist_ok=True)
            with open(os.path.join(gdir, "index.md"), "w", encoding="utf-8") as f:
                f.write(group_index_page(gkey, GROUPS[gkey], members, anim_data, locale))
            for c in members:
                with open(os.path.join(gdir, slug(c) + ".md"), "w", encoding="utf-8") as f:
                    f.write(creature_page(c, gkey, anim_data, sounds_data, appearance, locale))
                pages += 1

        os.makedirs(base, exist_ok=True)
        with open(os.path.join(base, "index.md"), "w", encoding="utf-8") as f:
            f.write(index_page(grouped, creatures, anim_data, locale))

        print(f"[{locale}] wrote {pages} creature pages + {len(grouped)} group indexes + 1 bestiary index")
    for gkey in GROUPS:
        print(f"  {gkey}: {len(grouped.get(gkey, []))}")


if __name__ == "__main__":
    main()
