#!/usr/bin/env python3
"""Generate the item catalog under src/content/docs/items/catalog/ from
data/items.json.

Produces:
  catalog/index.md        — overview table of categories with counts + links
  catalog/<category>.md   — one page per category, grouped by subcategory,
                            each group an Icon | Name | Item ID | Weight table.

All generated pages carry `generated: true` and the AUTO-GENERATED banner;
never hand-edit them — fix tools/extract_items.py or the source data and
regenerate. Only banner-marked files in catalog/ are deleted before
regeneration.

Usage: python3 tools/gen_items.py
"""

import datetime
import json
import os
import re
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(ROOT, "data", "items.json")
OUT_DIR = os.path.join(ROOT, "src", "content", "docs", "items", "catalog")

BANNER = ("<!-- AUTO-GENERATED by tools/gen_items.py from data/items.json"
          " — do not hand-edit -->")
TODAY = datetime.date.today().isoformat()


def slugify(name):
    s = name.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "misc"


def md_escape(s):
    """Make a string safe inside a markdown table cell (and for Starlight)."""
    return (str(s).replace("\\", "\\\\")
                  .replace("|", "\\|")
                  .replace("<", "&lt;")
                  .replace(">", "&gt;")
                  .replace("{", "&#123;")
                  .replace("}", "&#125;")
                  .replace("\n", " ")
                  .strip())


def frontmatter(title, description, sources):
    lines = [
        "---",
        "title: %s" % json.dumps(title),
        "description: %s" % json.dumps(description),
        "status: source-verified",
        "generated: true",
        "sources:",
    ]
    lines += ['  - "%s"' % s for s in sources]
    lines += ["last_verified: %s" % TODAY, "---", "", BANNER, ""]
    return "\n".join(lines)


def icon_cell(png):
    if not png:
        return ""
    return ('<img src="%s" class="uo-sprite" alt="" width="48" '
            'loading="lazy" />' % png)


def weight_cell(weight):
    if weight is None:
        return "—"
    if isinstance(weight, float) and weight == int(weight):
        weight = int(weight)
    return str(weight)


def clean_generated(out_dir):
    """Delete only banner-marked .md files in out_dir."""
    if not os.path.isdir(out_dir):
        return 0
    removed = 0
    for fn in os.listdir(out_dir):
        if not fn.endswith(".md"):
            continue
        p = os.path.join(out_dir, fn)
        try:
            text = open(p, encoding="utf-8").read()
        except OSError:
            continue
        if "AUTO-GENERATED" in text:
            os.remove(p)
            removed += 1
    return removed


def write_category_page(out_dir, category, items):
    """One page per category, grouped by subcategory."""
    slug = slugify(category)
    # group by subcategory, preserving the sorted order from items.json
    groups = OrderedDict()
    for it in items:
        sub = it["subcategory"] or "General"
        groups.setdefault(sub, []).append(it)

    title = "%s Items" % category
    description = ("Every %s item in the ServUO source (%d), with art, item "
                   "IDs and weights." % (category, len(items)))
    sources = ["servuo: Scripts/Items/%s" % category,
               "client: artLegacyMUL.uop"]

    out = [frontmatter(title, description, sources)]
    out.append("Auto-generated catalog of every concrete item class under "
               "`Scripts/Items/%s/` (%d items). Icons are static art from the "
               "client; item IDs are the resolved ServUO `ItemID`.\n" % (category, len(items)))

    for sub, rows in groups.items():
        out.append("## %s\n" % md_escape(sub))
        out.append("| Icon | Name | Item ID | Weight |")
        out.append("|------|------|---------|--------|")
        for it in rows:
            out.append("| %s | %s | `%s` | %s |" % (
                icon_cell(it["png"]),
                md_escape(it["name"]),
                it["item_id"],
                weight_cell(it["weight"]),
            ))
        out.append("")

    with open(os.path.join(out_dir, "%s.md" % slug), "w") as f:
        f.write("\n".join(out).rstrip() + "\n")
    return slug


def write_index(out_dir, by_category, cat_slugs, total):
    title = "Item Catalog"
    description = ("Image-rich catalog of every item in the ServUO source, "
                   "grouped by category.")
    sources = ["servuo: Scripts/Items", "client: artLegacyMUL.uop"]
    out = [frontmatter(title, description, sources)]
    out.append("A complete, auto-generated catalog of every concrete item "
               "class in the ServUO source — %d items across %d categories. "
               "Each category page lists items with their client art, item ID "
               "and weight, grouped by subcategory.\n"
               % (total, len(by_category)))
    out.append("This catalog is regenerated from `data/items.json` by "
               "`tools/gen_items.py`; do not hand-edit the category pages.\n")
    out.append("| Category | Items |")
    out.append("|----------|-------|")
    for cat in sorted(by_category):
        out.append("| [%s](/items/catalog/%s/) | %d |"
                   % (md_escape(cat), cat_slugs[cat], by_category[cat]))
    out.append("| **Total** | **%d** |" % total)
    out.append("")
    with open(os.path.join(out_dir, "index.md"), "w") as f:
        f.write("\n".join(out).rstrip() + "\n")


def main():
    doc = json.load(open(DATA_PATH))
    items = doc["items"]
    by_category = doc["_meta"]["by_category"]

    os.makedirs(OUT_DIR, exist_ok=True)
    removed = clean_generated(OUT_DIR)
    if removed:
        print("removed %d stale generated page(s)" % removed)

    # bucket items by category (already globally sorted)
    cat_items = OrderedDict()
    for it in items:
        cat_items.setdefault(it["category"], []).append(it)

    cat_slugs = {}
    for cat, rows in cat_items.items():
        slug = write_category_page(OUT_DIR, cat, rows)
        cat_slugs[cat] = slug
        print("  %-14s -> catalog/%s.md (%d items)" % (cat, slug, len(rows)))

    write_index(OUT_DIR, by_category, cat_slugs, len(items))

    print("\nwrote catalog/index.md + %d category pages (%d items total)"
          % (len(cat_slugs), len(items)))
    print("category slugs: %s"
          % ", ".join("%s=%s" % (c, s) for c, s in sorted(cat_slugs.items())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
