import { defineCollection, z } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

export const collections = {
	docs: defineCollection({
		loader: docsLoader(),
		schema: docsSchema({
			extend: z.object({
				// Provenance metadata — see CLAUDE.md for the verification lifecycle.
				status: z
					.enum(['draft', 'unverified', 'source-verified', 'field-verified'])
					.default('draft'),
				// Where each claim comes from, e.g. "servuo: Scripts/Skills/AnimalTaming.cs"
				// or "in-game: bjorn 2026-06-09".
				sources: z.array(z.string()).default([]),
				last_verified: z.coerce.date().optional(),
				// True on pages regenerated by tools/gen_pages.py — never hand-edit those.
				generated: z.boolean().default(false),
			}),
		}),
	}),
};
